// ─────────────────────────────────────────────────────────────────────────────
// Logo Bingo — course database
// ─────────────────────────────────────────────────────────────────────────────
// Curated subset of well-known courses from Golf Magazine's Top 100 in the
// World list. Quality over quantity: every entry is a course we're confident
// is on (or has been on) the GM Top 100 World list within the past decade.
//
// Each entry:
//   id        — kebab-case slug (stable; used as the asset filename later)
//   name      — full official name
//   shortName — common form
//   aliases   — extra strings that should match in the autocomplete
//   location  — "City, State/Country"
//   architect — primary designer (or "—" if unknown / unattributed)
//   logo      — emoji placeholder (varied + on-theme); replaced by /assets/logos/{id}.png if present
//   logoUrl   — empty string; runtime falls back to the emoji when no image
//
// IMPORTANT: real logo PNGs will replace the emoji once commissioned. Until
// then, the in-app renderer should call `courseLogoUrl(course)` and fall
// through to `course.logo` when the image 404s.
// ─────────────────────────────────────────────────────────────────────────────

export const COURSES = [
  // ── United States ────────────────────────────────────────────────────────
  {
    id: 'augusta-national',
    name: 'Augusta National Golf Club',
    shortName: 'Augusta National',
    aliases: ['augusta', 'the masters', 'national', 'augusta national gc'],
    location: 'Augusta, Georgia',
    architect: 'Alister MacKenzie & Bobby Jones',
    logo: '🌷',
    logoUrl: '',
  },
  {
    id: 'pine-valley',
    name: 'Pine Valley Golf Club',
    shortName: 'Pine Valley',
    aliases: ['pine valley gc'],
    location: 'Pine Valley, New Jersey',
    architect: 'George Crump',
    logo: '🌲',
    logoUrl: '',
  },
  {
    id: 'cypress-point',
    name: 'Cypress Point Club',
    shortName: 'Cypress Point',
    aliases: ['cypress', 'cypress point cc'],
    location: 'Pebble Beach, California',
    architect: 'Alister MacKenzie',
    logo: '🌲',
    logoUrl: '',
  },
  {
    id: 'pebble-beach',
    name: 'Pebble Beach Golf Links',
    shortName: 'Pebble Beach',
    aliases: ['pebble', 'pebble beach gl'],
    location: 'Pebble Beach, California',
    architect: 'Jack Neville & Douglas Grant',
    logo: '🌊',
    logoUrl: '',
  },
  {
    id: 'shinnecock-hills',
    name: 'Shinnecock Hills Golf Club',
    shortName: 'Shinnecock Hills',
    aliases: ['shinnecock', 'shinnecock hills gc'],
    location: 'Southampton, New York',
    architect: 'William Flynn',
    logo: '⛳',
    logoUrl: '',
  },
  {
    id: 'oakmont',
    name: 'Oakmont Country Club',
    shortName: 'Oakmont',
    aliases: ['oakmont cc'],
    location: 'Oakmont, Pennsylvania',
    architect: 'Henry Fownes',
    logo: '⛳',
    logoUrl: '',
  },
  {
    id: 'merion-east',
    name: 'Merion Golf Club (East)',
    shortName: 'Merion East',
    aliases: ['merion', 'merion gc', 'merion east course'],
    location: 'Ardmore, Pennsylvania',
    architect: 'Hugh Wilson',
    logo: '🧺',
    logoUrl: '',
  },
  {
    id: 'national-golf-links',
    name: 'National Golf Links of America',
    shortName: 'National Golf Links',
    aliases: ['ngla', 'national golf links of america'],
    location: 'Southampton, New York',
    architect: 'C.B. Macdonald',
    logo: '🇺🇸',
    logoUrl: '',
  },
  {
    id: 'fishers-island',
    name: 'Fishers Island Club',
    shortName: 'Fishers Island',
    aliases: ['fishers', 'fishers island club', 'fic'],
    location: 'Fishers Island, New York',
    architect: 'Seth Raynor',
    logo: '🐟',
    logoUrl: '',
  },
  {
    id: 'sand-hills',
    name: 'Sand Hills Golf Club',
    shortName: 'Sand Hills',
    aliases: ['sand hills gc'],
    location: 'Mullen, Nebraska',
    architect: 'Bill Coore & Ben Crenshaw',
    logo: '🏜️',
    logoUrl: '',
  },
  {
    id: 'pacific-dunes',
    name: 'Pacific Dunes',
    shortName: 'Pacific Dunes',
    aliases: ['bandon pacific dunes', 'pacific dunes bandon'],
    location: 'Bandon, Oregon',
    architect: 'Tom Doak',
    logo: '🌊',
    logoUrl: '',
  },
  {
    id: 'bandon-dunes',
    name: 'Bandon Dunes Golf Course',
    shortName: 'Bandon Dunes',
    aliases: ['bandon', 'bandon dunes gc'],
    location: 'Bandon, Oregon',
    architect: 'David McLay Kidd',
    logo: '🏖️',
    logoUrl: '',
  },
  {
    id: 'old-macdonald',
    name: 'Old Macdonald',
    shortName: 'Old Macdonald',
    aliases: ['bandon old macdonald', 'old mac'],
    location: 'Bandon, Oregon',
    architect: 'Tom Doak & Jim Urbina',
    logo: '🌾',
    logoUrl: '',
  },
  {
    id: 'bandon-trails',
    name: 'Bandon Trails',
    shortName: 'Bandon Trails',
    aliases: ['trails'],
    location: 'Bandon, Oregon',
    architect: 'Bill Coore & Ben Crenshaw',
    logo: '🥾',
    logoUrl: '',
  },
  {
    id: 'sheep-ranch',
    name: 'Sheep Ranch',
    shortName: 'Sheep Ranch',
    aliases: ['bandon sheep ranch'],
    location: 'Bandon, Oregon',
    architect: 'Bill Coore & Ben Crenshaw',
    logo: '🐑',
    logoUrl: '',
  },
  {
    id: 'chicago-golf-club',
    name: 'Chicago Golf Club',
    shortName: 'Chicago Golf Club',
    aliases: ['chicago gc', 'cgc'],
    location: 'Wheaton, Illinois',
    architect: 'C.B. Macdonald & Seth Raynor',
    logo: '🏙️',
    logoUrl: '',
  },
  {
    id: 'winged-foot-west',
    name: 'Winged Foot Golf Club (West)',
    shortName: 'Winged Foot West',
    aliases: ['winged foot', 'winged foot west course', 'wfgc'],
    location: 'Mamaroneck, New York',
    architect: 'A.W. Tillinghast',
    logo: '🦅',
    logoUrl: '',
  },
  {
    id: 'seminole',
    name: 'Seminole Golf Club',
    shortName: 'Seminole',
    aliases: ['seminole gc'],
    location: 'Juno Beach, Florida',
    architect: 'Donald Ross',
    logo: '🌴',
    logoUrl: '',
  },
  {
    id: 'los-angeles-cc-north',
    name: 'Los Angeles Country Club (North)',
    shortName: 'LACC North',
    aliases: ['lacc', 'la country club', 'los angeles cc', 'lacc north course'],
    location: 'Los Angeles, California',
    architect: 'George C. Thomas Jr.',
    logo: '🌴',
    logoUrl: '',
  },
  {
    id: 'riviera',
    name: 'The Riviera Country Club',
    shortName: 'Riviera',
    aliases: ['riviera cc', 'the riv'],
    location: 'Pacific Palisades, California',
    architect: 'George C. Thomas Jr.',
    logo: '🎬',
    logoUrl: '',
  },
  {
    id: 'oakland-hills-south',
    name: 'Oakland Hills Country Club (South)',
    shortName: 'Oakland Hills South',
    aliases: ['oakland hills', 'oakland hills cc'],
    location: 'Bloomfield Hills, Michigan',
    architect: 'Donald Ross',
    logo: '🐉',
    logoUrl: '',
  },
  {
    id: 'olympic-club-lake',
    name: 'The Olympic Club (Lake)',
    shortName: 'Olympic Club Lake',
    aliases: ['olympic club', 'the olympic club', 'olympic lake'],
    location: 'San Francisco, California',
    architect: 'Sam Whiting',
    logo: '🏛️',
    logoUrl: '',
  },
  {
    id: 'san-francisco-gc',
    name: 'San Francisco Golf Club',
    shortName: 'San Francisco GC',
    aliases: ['sfgc', 'san francisco golf club'],
    location: 'San Francisco, California',
    architect: 'A.W. Tillinghast',
    logo: '🌉',
    logoUrl: '',
  },
  {
    id: 'baltusrol-lower',
    name: 'Baltusrol Golf Club (Lower)',
    shortName: 'Baltusrol Lower',
    aliases: ['baltusrol', 'baltusrol gc', 'baltusrol lower course'],
    location: 'Springfield, New Jersey',
    architect: 'A.W. Tillinghast',
    logo: '⛳',
    logoUrl: '',
  },
  {
    id: 'bethpage-black',
    name: 'Bethpage State Park (Black)',
    shortName: 'Bethpage Black',
    aliases: ['bethpage', 'the black', 'bethpage black course'],
    location: 'Farmingdale, New York',
    architect: 'A.W. Tillinghast',
    logo: '⚫',
    logoUrl: '',
  },
  {
    id: 'pinehurst-no-2',
    name: 'Pinehurst No. 2',
    shortName: 'Pinehurst No. 2',
    aliases: ['pinehurst 2', 'pinehurst', 'pinehurst number 2', 'pinehurst #2'],
    location: 'Pinehurst, North Carolina',
    architect: 'Donald Ross',
    logo: '🌲',
    logoUrl: '',
  },
  {
    id: 'whistling-straits',
    name: 'Whistling Straits (Straits)',
    shortName: 'Whistling Straits',
    aliases: ['whistling straits straits', 'the straits', 'whistling straits gc'],
    location: 'Haven, Wisconsin',
    architect: 'Pete Dye',
    logo: '🌬️',
    logoUrl: '',
  },
  {
    id: 'erin-hills',
    name: 'Erin Hills',
    shortName: 'Erin Hills',
    aliases: ['erin hills gc'],
    location: 'Erin, Wisconsin',
    architect: 'Hurdzan, Fry & Whitten',
    logo: '🌾',
    logoUrl: '',
  },
  {
    id: 'tpc-sawgrass',
    name: 'TPC Sawgrass (Stadium)',
    shortName: 'TPC Sawgrass',
    aliases: ['sawgrass', 'players stadium course', 'tpc sawgrass stadium'],
    location: 'Ponte Vedra Beach, Florida',
    architect: 'Pete Dye',
    logo: '🏝️',
    logoUrl: '',
  },
  {
    id: 'kiawah-ocean',
    name: 'Kiawah Island Golf Resort (Ocean)',
    shortName: 'Kiawah Ocean Course',
    aliases: ['kiawah', 'the ocean course', 'kiawah ocean'],
    location: 'Kiawah Island, South Carolina',
    architect: 'Pete Dye',
    logo: '🌊',
    logoUrl: '',
  },
  {
    id: 'harbour-town',
    name: 'Harbour Town Golf Links',
    shortName: 'Harbour Town',
    aliases: ['harbour town gl', 'sea pines harbour town'],
    location: 'Hilton Head, South Carolina',
    architect: 'Pete Dye & Jack Nicklaus',
    logo: '🚤',
    logoUrl: '',
  },
  {
    id: 'tobacco-road',
    name: 'Tobacco Road Golf Club',
    shortName: 'Tobacco Road',
    aliases: ['tobacco road gc'],
    location: 'Sanford, North Carolina',
    architect: 'Mike Strantz',
    logo: '🚬',
    logoUrl: '',
  },
  {
    id: 'streamsong-red',
    name: 'Streamsong Resort (Red)',
    shortName: 'Streamsong Red',
    aliases: ['streamsong red course'],
    location: 'Bowling Green, Florida',
    architect: 'Bill Coore & Ben Crenshaw',
    logo: '🟥',
    logoUrl: '',
  },
  {
    id: 'streamsong-blue',
    name: 'Streamsong Resort (Blue)',
    shortName: 'Streamsong Blue',
    aliases: ['streamsong blue course'],
    location: 'Bowling Green, Florida',
    architect: 'Tom Doak',
    logo: '🟦',
    logoUrl: '',
  },
  {
    id: 'streamsong-black',
    name: 'Streamsong Resort (Black)',
    shortName: 'Streamsong Black',
    aliases: ['streamsong black course'],
    location: 'Bowling Green, Florida',
    architect: 'Gil Hanse',
    logo: '⬛',
    logoUrl: '',
  },
  {
    id: 'cabot-citrus-farms',
    name: 'Cabot Citrus Farms',
    shortName: 'Cabot Citrus Farms',
    aliases: ['cabot citrus', 'world woods', 'pine barrens cabot'],
    location: 'Brooksville, Florida',
    architect: 'Kyle Franz / Mike Strantz',
    logo: '🍊',
    logoUrl: '',
  },
  {
    id: 'inverness',
    name: 'Inverness Club',
    shortName: 'Inverness',
    aliases: ['inverness club'],
    location: 'Toledo, Ohio',
    architect: 'Donald Ross',
    logo: '⛳',
    logoUrl: '',
  },
  {
    id: 'crystal-downs',
    name: 'Crystal Downs Country Club',
    shortName: 'Crystal Downs',
    aliases: ['crystal downs cc'],
    location: 'Frankfort, Michigan',
    architect: 'Alister MacKenzie & Perry Maxwell',
    logo: '💎',
    logoUrl: '',
  },
  {
    id: 'prairie-dunes',
    name: 'Prairie Dunes Country Club',
    shortName: 'Prairie Dunes',
    aliases: ['prairie dunes cc'],
    location: 'Hutchinson, Kansas',
    architect: 'Perry Maxwell',
    logo: '🌾',
    logoUrl: '',
  },
  {
    id: 'oak-hill-east',
    name: 'Oak Hill Country Club (East)',
    shortName: 'Oak Hill East',
    aliases: ['oak hill', 'oak hill cc'],
    location: 'Rochester, New York',
    architect: 'Donald Ross',
    logo: '🌳',
    logoUrl: '',
  },
  {
    id: 'medinah-3',
    name: 'Medinah Country Club (No. 3)',
    shortName: 'Medinah No. 3',
    aliases: ['medinah', 'medinah cc', 'medinah 3'],
    location: 'Medinah, Illinois',
    architect: 'Tom Bendelow',
    logo: '🕌',
    logoUrl: '',
  },
  {
    id: 'quaker-ridge',
    name: 'Quaker Ridge Golf Club',
    shortName: 'Quaker Ridge',
    aliases: ['quaker ridge gc'],
    location: 'Scarsdale, New York',
    architect: 'A.W. Tillinghast',
    logo: '🎩',
    logoUrl: '',
  },
  {
    id: 'wade-hampton',
    name: 'Wade Hampton Golf Club',
    shortName: 'Wade Hampton',
    aliases: ['wade hampton gc'],
    location: 'Cashiers, North Carolina',
    architect: 'Tom Fazio',
    logo: '⛰️',
    logoUrl: '',
  },
  {
    id: 'east-lake',
    name: 'East Lake Golf Club',
    shortName: 'East Lake',
    aliases: ['east lake gc', 'tour championship'],
    location: 'Atlanta, Georgia',
    architect: 'Donald Ross / Rees Jones',
    logo: '🏆',
    logoUrl: '',
  },
  {
    id: 'whispering-pines',
    name: 'Whispering Pines Golf Club',
    shortName: 'Whispering Pines',
    aliases: ['whispering pines gc'],
    location: 'Trinity, Texas',
    architect: 'Chet Williams',
    logo: '🌲',
    logoUrl: '',
  },
  {
    id: 'castle-pines',
    name: 'Castle Pines Golf Club',
    shortName: 'Castle Pines',
    aliases: ['castle pines gc'],
    location: 'Castle Rock, Colorado',
    architect: 'Jack Nicklaus',
    logo: '🏰',
    logoUrl: '',
  },
  {
    id: 'shadow-creek',
    name: 'Shadow Creek',
    shortName: 'Shadow Creek',
    aliases: ['shadow creek gc'],
    location: 'North Las Vegas, Nevada',
    architect: 'Tom Fazio',
    logo: '🌑',
    logoUrl: '',
  },
  {
    id: 'friars-head',
    name: "Friar's Head",
    shortName: "Friar's Head",
    aliases: ['friars head', 'friars head gc'],
    location: 'Baiting Hollow, New York',
    architect: 'Bill Coore & Ben Crenshaw',
    logo: '⛪',
    logoUrl: '',
  },
  {
    id: 'somerset-hills',
    name: 'Somerset Hills Country Club',
    shortName: 'Somerset Hills',
    aliases: ['somerset hills cc'],
    location: 'Bernardsville, New Jersey',
    architect: 'A.W. Tillinghast',
    logo: '🏞️',
    logoUrl: '',
  },
  {
    id: 'maidstone',
    name: 'Maidstone Club',
    shortName: 'Maidstone',
    aliases: ['maidstone club'],
    location: 'East Hampton, New York',
    architect: 'Willie & John Park Jr.',
    logo: '🏖️',
    logoUrl: '',
  },

  // ── Scotland ─────────────────────────────────────────────────────────────
  {
    id: 'st-andrews-old',
    name: 'The Old Course at St Andrews',
    shortName: 'St Andrews (Old)',
    aliases: ['st andrews', 'old course', 'the old course', 'st andrews old course', 'home of golf'],
    location: 'St Andrews, Scotland',
    architect: 'Old Tom Morris (evolved)',
    logo: '🏰',
    logoUrl: '',
  },
  {
    id: 'muirfield',
    name: 'Muirfield (The Honourable Company of Edinburgh Golfers)',
    shortName: 'Muirfield',
    aliases: ['muirfield gc', 'honourable company of edinburgh golfers', 'the honourable company'],
    location: 'Gullane, Scotland',
    architect: 'Old Tom Morris / Harry Colt',
    logo: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    logoUrl: '',
  },
  {
    id: 'royal-dornoch',
    name: 'Royal Dornoch Golf Club (Championship)',
    shortName: 'Royal Dornoch',
    aliases: ['dornoch', 'royal dornoch gc'],
    location: 'Dornoch, Scotland',
    architect: 'Old Tom Morris / John Sutherland',
    logo: '👑',
    logoUrl: '',
  },
  {
    id: 'turnberry-ailsa',
    name: 'Trump Turnberry (Ailsa)',
    shortName: 'Turnberry (Ailsa)',
    aliases: ['turnberry', 'ailsa', 'trump turnberry', 'turnberry ailsa course'],
    location: 'Turnberry, Scotland',
    architect: 'Mackenzie Ross',
    logo: '🗼',
    logoUrl: '',
  },
  {
    id: 'carnoustie',
    name: 'Carnoustie Golf Links (Championship)',
    shortName: 'Carnoustie',
    aliases: ['carnoustie championship', 'car-nasty', 'carnoustie gl'],
    location: 'Carnoustie, Scotland',
    architect: 'James Braid',
    logo: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    logoUrl: '',
  },
  {
    id: 'north-berwick',
    name: 'North Berwick (West Links)',
    shortName: 'North Berwick',
    aliases: ['north berwick west', 'north berwick gc', 'west links'],
    location: 'North Berwick, Scotland',
    architect: '—',
    logo: '🪨',
    logoUrl: '',
  },
  {
    id: 'kingsbarns',
    name: 'Kingsbarns Golf Links',
    shortName: 'Kingsbarns',
    aliases: ['kingsbarns gl'],
    location: 'St Andrews, Scotland',
    architect: 'Kyle Phillips',
    logo: '🌊',
    logoUrl: '',
  },
  {
    id: 'cruden-bay',
    name: 'Cruden Bay Golf Club',
    shortName: 'Cruden Bay',
    aliases: ['cruden bay gc'],
    location: 'Cruden Bay, Scotland',
    architect: 'Old Tom Morris / Tom Simpson',
    logo: '🌅',
    logoUrl: '',
  },
  {
    id: 'machrihanish',
    name: 'Machrihanish Golf Club',
    shortName: 'Machrihanish',
    aliases: ['machrihanish gc', 'old mach'],
    location: 'Campbeltown, Scotland',
    architect: 'Old Tom Morris',
    logo: '🪶',
    logoUrl: '',
  },
  {
    id: 'machrihanish-dunes',
    name: 'Machrihanish Dunes',
    shortName: 'Machrihanish Dunes',
    aliases: ['mach dunes'],
    location: 'Campbeltown, Scotland',
    architect: 'David McLay Kidd',
    logo: '🏞️',
    logoUrl: '',
  },
  {
    id: 'castle-stuart',
    name: 'Castle Stuart Golf Links',
    shortName: 'Castle Stuart',
    aliases: ['castle stuart gl'],
    location: 'Inverness, Scotland',
    architect: 'Gil Hanse & Mark Parsinen',
    logo: '🏰',
    logoUrl: '',
  },
  {
    id: 'royal-troon',
    name: 'Royal Troon Golf Club (Old)',
    shortName: 'Royal Troon',
    aliases: ['troon', 'royal troon gc', 'royal troon old'],
    location: 'Troon, Scotland',
    architect: 'Willie Fernie',
    logo: '👑',
    logoUrl: '',
  },

  // ── England, Wales, Northern Ireland & Ireland ───────────────────────────
  {
    id: 'royal-county-down',
    name: 'Royal County Down Golf Club (Championship)',
    shortName: 'Royal County Down',
    aliases: ['rcd', 'royal county down gc', 'county down'],
    location: 'Newcastle, Northern Ireland',
    architect: 'Old Tom Morris / Harry Vardon',
    logo: '⛰️',
    logoUrl: '',
  },
  {
    id: 'royal-portrush-dunluce',
    name: 'Royal Portrush Golf Club (Dunluce)',
    shortName: 'Royal Portrush',
    aliases: ['portrush', 'royal portrush dunluce', 'dunluce'],
    location: 'Portrush, Northern Ireland',
    architect: 'Harry Colt',
    logo: '🏰',
    logoUrl: '',
  },
  {
    id: 'ballybunion-old',
    name: 'Ballybunion Golf Club (Old)',
    shortName: 'Ballybunion (Old)',
    aliases: ['ballybunion', 'ballybunion old course'],
    location: 'Ballybunion, Ireland',
    architect: 'Tom Simpson (revisions)',
    logo: '🍀',
    logoUrl: '',
  },
  {
    id: 'lahinch',
    name: 'Lahinch Golf Club',
    shortName: 'Lahinch',
    aliases: ['lahinch gc', 'old course lahinch'],
    location: 'Lahinch, Ireland',
    architect: 'Old Tom Morris / Alister MacKenzie',
    logo: '🐐',
    logoUrl: '',
  },
  {
    id: 'portmarnock',
    name: 'Portmarnock Golf Club',
    shortName: 'Portmarnock',
    aliases: ['portmarnock gc'],
    location: 'Portmarnock, Ireland',
    architect: 'W.C. Pickeman / Mungo Park',
    logo: '☘️',
    logoUrl: '',
  },
  {
    id: 'european-club',
    name: 'The European Club',
    shortName: 'European Club',
    aliases: ['european club ireland'],
    location: 'Brittas Bay, Ireland',
    architect: 'Pat Ruddy',
    logo: '🇪🇺',
    logoUrl: '',
  },
  {
    id: 'royal-st-georges',
    name: "Royal St George's Golf Club",
    shortName: "Royal St George's",
    aliases: ['royal st georges', 'sandwich', 'rsg'],
    location: 'Sandwich, England',
    architect: 'William Laidlaw Purves',
    logo: '🐉',
    logoUrl: '',
  },
  {
    id: 'sunningdale-old',
    name: 'Sunningdale Golf Club (Old)',
    shortName: 'Sunningdale Old',
    aliases: ['sunningdale', 'sunningdale gc', 'sunningdale old course'],
    location: 'Sunningdale, England',
    architect: 'Willie Park Jr.',
    logo: '☀️',
    logoUrl: '',
  },
  {
    id: 'royal-birkdale',
    name: 'Royal Birkdale Golf Club',
    shortName: 'Royal Birkdale',
    aliases: ['birkdale', 'royal birkdale gc'],
    location: 'Southport, England',
    architect: 'George Lowe / F.G. Hawtree',
    logo: '🌾',
    logoUrl: '',
  },
  {
    id: 'royal-lytham',
    name: "Royal Lytham & St Annes Golf Club",
    shortName: "Royal Lytham",
    aliases: ['royal lytham and st annes', 'lytham', 'royal lytham gc'],
    location: 'Lytham St Annes, England',
    architect: 'George Lowe',
    logo: '⛳',
    logoUrl: '',
  },
  {
    id: 'royal-liverpool',
    name: 'Royal Liverpool Golf Club',
    shortName: 'Royal Liverpool',
    aliases: ['hoylake', 'royal liverpool gc'],
    location: 'Hoylake, England',
    architect: 'Robert Chambers / George Morris',
    logo: '🐦',
    logoUrl: '',
  },
  {
    id: 'swinley-forest',
    name: 'Swinley Forest Golf Club',
    shortName: 'Swinley Forest',
    aliases: ['swinley', 'swinley forest gc'],
    location: 'Ascot, England',
    architect: 'Harry Colt',
    logo: '🌲',
    logoUrl: '',
  },
  {
    id: 'walton-heath-old',
    name: 'Walton Heath Golf Club (Old)',
    shortName: 'Walton Heath',
    aliases: ['walton heath', 'walton heath old course', 'walton heath gc'],
    location: 'Walton-on-the-Hill, England',
    architect: 'Herbert Fowler',
    logo: '🌿',
    logoUrl: '',
  },

  // ── Continental Europe ───────────────────────────────────────────────────
  {
    id: 'morfontaine',
    name: 'Golf de Morfontaine',
    shortName: 'Morfontaine',
    aliases: ['morfontaine gc'],
    location: 'Mortefontaine, France',
    architect: 'Tom Simpson',
    logo: '🥖',
    logoUrl: '',
  },
  {
    id: 'les-bordes',
    name: 'Les Bordes Golf Club',
    shortName: 'Les Bordes',
    aliases: ['les bordes gc'],
    location: 'Saint-Laurent-Nouan, France',
    architect: 'Robert von Hagge',
    logo: '🍇',
    logoUrl: '',
  },
  {
    id: 'valderrama',
    name: 'Real Club Valderrama',
    shortName: 'Valderrama',
    aliases: ['valderrama gc', 'rc valderrama'],
    location: 'Sotogrande, Spain',
    architect: 'Robert Trent Jones Sr.',
    logo: '🫒',
    logoUrl: '',
  },

  // ── Australia & New Zealand ──────────────────────────────────────────────
  {
    id: 'royal-melbourne-west',
    name: 'Royal Melbourne Golf Club (West)',
    shortName: 'Royal Melbourne (West)',
    aliases: ['royal melbourne', 'royal melbourne gc', 'rmgc', 'royal melbourne west course'],
    location: 'Black Rock, Australia',
    architect: 'Alister MacKenzie',
    logo: '🦘',
    logoUrl: '',
  },
  {
    id: 'kingston-heath',
    name: 'Kingston Heath Golf Club',
    shortName: 'Kingston Heath',
    aliases: ['kingston heath gc'],
    location: 'Cheltenham, Australia',
    architect: 'Dan Soutar / Alister MacKenzie',
    logo: '🌿',
    logoUrl: '',
  },
  {
    id: 'barnbougle-dunes',
    name: 'Barnbougle Dunes',
    shortName: 'Barnbougle Dunes',
    aliases: ['barnbougle'],
    location: 'Bridport, Tasmania, Australia',
    architect: 'Tom Doak & Mike Clayton',
    logo: '🌊',
    logoUrl: '',
  },
  {
    id: 'barnbougle-lost-farm',
    name: 'Barnbougle Lost Farm',
    shortName: 'Lost Farm',
    aliases: ['barnbougle lost farm', 'lost farm'],
    location: 'Bridport, Tasmania, Australia',
    architect: 'Bill Coore & Ben Crenshaw',
    logo: '🚜',
    logoUrl: '',
  },
  {
    id: 'cape-wickham',
    name: 'Cape Wickham Links',
    shortName: 'Cape Wickham',
    aliases: ['cape wickham links'],
    location: 'King Island, Australia',
    architect: 'Mike DeVries & Darius Oliver',
    logo: '🌬️',
    logoUrl: '',
  },
  {
    id: 'new-south-wales',
    name: 'New South Wales Golf Club',
    shortName: 'New South Wales',
    aliases: ['nsw gc', 'new south wales gc'],
    location: 'La Perouse, Australia',
    architect: 'Alister MacKenzie',
    logo: '🌊',
    logoUrl: '',
  },
  {
    id: 'tara-iti',
    name: 'Tara Iti Golf Club',
    shortName: 'Tara Iti',
    aliases: ['tara iti gc'],
    location: 'Te Arai, New Zealand',
    architect: 'Tom Doak',
    logo: '🐦',
    logoUrl: '',
  },
  {
    id: 'cape-kidnappers',
    name: 'Cape Kidnappers',
    shortName: 'Cape Kidnappers',
    aliases: ['cape kidnappers gc', 'kidnappers'],
    location: "Hawke's Bay, New Zealand",
    architect: 'Tom Doak',
    logo: '🌊',
    logoUrl: '',
  },

  // ── Canada & Caribbean ───────────────────────────────────────────────────
  {
    id: 'cabot-cliffs',
    name: 'Cabot Cliffs',
    shortName: 'Cabot Cliffs',
    aliases: ['cabot cliffs gc'],
    location: 'Inverness, Nova Scotia, Canada',
    architect: 'Bill Coore & Ben Crenshaw',
    logo: '🧗',
    logoUrl: '',
  },
  {
    id: 'cabot-links',
    name: 'Cabot Links',
    shortName: 'Cabot Links',
    aliases: ['cabot', 'cabot links gc'],
    location: 'Inverness, Nova Scotia, Canada',
    architect: 'Rod Whitman',
    logo: '🍁',
    logoUrl: '',
  },
  {
    id: 'st-georges-canada',
    name: "St. George's Golf and Country Club",
    shortName: "St. George's (Canada)",
    aliases: ['st georges canada', 'st georges gc canada'],
    location: 'Etobicoke, Ontario, Canada',
    architect: 'Stanley Thompson',
    logo: '🍁',
    logoUrl: '',
  },
  {
    id: 'hamilton-gcc',
    name: 'Hamilton Golf and Country Club',
    shortName: 'Hamilton G&CC',
    aliases: ['hamilton golf and country club', 'hamilton gcc'],
    location: 'Ancaster, Ontario, Canada',
    architect: 'Harry Colt',
    logo: '🍁',
    logoUrl: '',
  },

  // ── Asia ─────────────────────────────────────────────────────────────────
  {
    id: 'hirono',
    name: 'Hirono Golf Club',
    shortName: 'Hirono',
    aliases: ['hirono gc'],
    location: 'Kobe, Japan',
    architect: 'Charles Alison',
    logo: '🌸',
    logoUrl: '',
  },
  {
    id: 'kawana-fuji',
    name: 'Kawana Hotel (Fuji)',
    shortName: 'Kawana (Fuji)',
    aliases: ['kawana', 'kawana fuji course', 'kawana hotel fuji'],
    location: 'Itō, Japan',
    architect: 'Charles Alison',
    logo: '🗻',
    logoUrl: '',
  },
  {
    id: 'tokyo-gc',
    name: 'Tokyo Golf Club',
    shortName: 'Tokyo Golf Club',
    aliases: ['tokyo gc'],
    location: 'Sayama, Japan',
    architect: 'Komyo Otani',
    logo: '🗾',
    logoUrl: '',
  },
];

// Helper used by the runtime when rendering a tile. Returns either the
// configured logoUrl, or the conventional asset path; the caller falls back
// to the emoji if the <img> 404s.
export function courseLogoUrl(course) {
  if (!course) return '';
  if (course.logoUrl) return course.logoUrl;
  return `/assets/logos/${course.id}.png`;
}
