// ─────────────────────────────────────────────────────────────────────────────
// Logo Bingo — course database
// ─────────────────────────────────────────────────────────────────────────────
// Curated subset of well-known courses from Golf Magazine's Top 100 in the
// World list. Quality over quantity: every entry is a course we're confident
// is on (or has been on) the GM Top 100 World list within the past decade.
//
// Each entry:
//   id        — kebab-case slug (stable; used as the asset filename later)
//   name      — full official name
//   shortName — common form
//   aliases   — extra strings that should match in the autocomplete
//   location  — "City, State/Country"
//   architect — primary designer (or "—" if unknown / unattributed)
//   logo      — emoji placeholder (varied + on-theme); replaced by /assets/logos/{id}.png if present
//   logoUrl   — empty string; runtime falls back to the emoji when no image
//
// IMPORTANT: real logo PNGs will replace the emoji once commissioned. Until
// then, the in-app renderer should call `courseLogoUrl(course)` and fall
// through to `course.logo` when the image 404s.
// ─────────────────────────────────────────────────────────────────────────────

export const COURSES = [
  // ── United States ────────────────────────────────────────────────────────
  {
    id: 'augusta-national',
    name: 'Augusta National Golf Club',
    shortName: 'Augusta National',
    aliases: ['augusta', 'the masters', 'national', 'augusta national gc'],
    location: 'Augusta, Georgia',
    architect: 'Alister MacKenzie & Bobby Jones',
    logo: '🌷',
    logoUrl: '',
  },
  {
    id: 'pine-valley',
    name: 'Pine Valley Golf Club',
    shortName: 'Pine Valley',
    aliases: ['pine valley gc'],
    location: 'Pine Valley, New Jersey',
    architect: 'George Crump',
    logo: '🌲',
    logoUrl: '',
  },
  {
    id: 'cypress-point',
    name: 'Cypress Point Club',
    shortName: 'Cypress Point',
    aliases: ['cypress', 'cypress point cc'],
    location: 'Pebble Beach, California',
    architect: 'Alister MacKenzie',
    logo: '🌲',
    logoUrl: '',
  },
  {
    id: 'pebble-beach',
    name: 'Pebble Beach Golf Links',
    shortName: 'Pebble Beach',
    aliases: ['pebble', 'pebble beach gl'],
    location: 'Pebble Beach, California',
    architect: 'Jack Neville & Douglas Grant',
    logo: '🌊',
    logoUrl: '',
  },
  {
    id: 'shinnecock-hills',
    name: 'Shinnecock Hills Golf Club',
    shortName: 'Shinnecock Hills',
    aliases: ['shinnecock', 'shinnecock hills gc'],
    location: 'Southampton, New York',
    architect: 'William Flynn',
    logo: '⛳',
    logoUrl: '',
  },
  {
    id: 'oakmont',
    name: 'Oakmont Country Club',
    shortName: 'Oakmont',
    aliases: ['oakmont cc'],
    location: 'Oakmont, Pennsylvania',
    architect: 'Henry Fownes',
    logo: '⛳',
    logoUrl: '',
  },
  {
    id: 'merion-east',
    name: 'Merion Golf Club (East)',
    shortName: 'Merion East',
    aliases: ['merion', 'merion gc', 'merion east course'],
    location: 'Ardmore, Pennsylvania',
    architect: 'Hugh Wilson',
    logo: '🧺',
    logoUrl: '',
  },
  {
    id: 'national-golf-links',
    name: 'National Golf Links of America',
    shortName: 'National Golf Links',
    aliases: ['ngla', 'national golf links of america'],
    location: 'Southampton, New York',
    architect: 'C.B. Macdonald',
    logo: '🇺🇸',
    logoUrl: '',
  },
  {
    id: 'fishers-island',
    name: 'Fishers Island Club',
    shortName: 'Fishers Island',
    aliases: ['fishers', 'fishers island club', 'fic'],
    location: 'Fishers Island, New York',
    architect: 'Seth Raynor',
    logo: '🐟',
    logoUrl: '',
  },
  {
    id: 'sand-hills',
    name: 'Sand Hills Golf Club',
    shortName: 'Sand Hills',
    aliases: ['sand hills gc'],
    location: 'Mullen, Nebraska',
    architect: 'Bill Coore & Ben Crenshaw',
    logo: '🏜️',
    logoUrl: '',
  },
  {
    id: 'bandon-dunes',
    name: 'Bandon Dunes Resort',
    shortName: 'Bandon Dunes',
    // Consolidated from 5 individual courses (Pacific Dunes, Old Macdonald,
    // Bandon Trails, Sheep Ranch, Bandon Dunes) — they share one resort
    // logo, so as a guess-the-logo target they all map to the umbrella brand.
    aliases: ['bandon', 'bandon dunes', 'pacific dunes', 'old macdonald', 'bandon trails', 'sheep ranch'],
    location: 'Bandon, Oregon',
    architect: 'David McLay Kidd / Tom Doak / Coore & Crenshaw',
    logo: '🏖️',
    logoUrl: '',
  },
  {
    id: 'chicago-golf-club',
    name: 'Chicago Golf Club',
    shortName: 'Chicago Golf Club',
    aliases: ['chicago gc', 'cgc'],
    location: 'Wheaton, Illinois',
    architect: 'C.B. Macdonald & Seth Raynor',
    logo: '🏙️',
    logoUrl: '',
  },
  {
    id: 'winged-foot-west',
    name: 'Winged Foot Golf Club (West)',
    shortName: 'Winged Foot West',
    aliases: ['winged foot', 'winged foot west course', 'wfgc'],
    location: 'Mamaroneck, New York',
    architect: 'A.W. Tillinghast',
    logo: '🦅',
    logoUrl: '',
  },
  {
    id: 'seminole',
    name: 'Seminole Golf Club',
    shortName: 'Seminole',
    aliases: ['seminole gc'],
    location: 'Juno Beach, Florida',
    architect: 'Donald Ross',
    logo: '🌴',
    logoUrl: '',
  },
  {
    id: 'los-angeles-cc-north',
    name: 'Los Angeles Country Club (North)',
    shortName: 'LACC North',
    aliases: ['lacc', 'la country club', 'los angeles cc', 'lacc north course'],
    location: 'Los Angeles, California',
    architect: 'George C. Thomas Jr.',
    logo: '🌴',
    logoUrl: '',
  },
  {
    id: 'riviera',
    name: 'The Riviera Country Club',
    shortName: 'Riviera',
    aliases: ['riviera cc', 'the riv'],
    location: 'Pacific Palisades, California',
    architect: 'George C. Thomas Jr.',
    logo: '🎬',
    logoUrl: '',
  },
  {
    id: 'oakland-hills-south',
    name: 'Oakland Hills Country Club (South)',
    shortName: 'Oakland Hills South',
    aliases: ['oakland hills', 'oakland hills cc'],
    location: 'Bloomfield Hills, Michigan',
    architect: 'Donald Ross',
    logo: '🐉',
    logoUrl: '',
  },
  {
    id: 'olympic-club-lake',
    name: 'The Olympic Club (Lake)',
    shortName: 'Olympic Club Lake',
    aliases: ['olympic club', 'the olympic club', 'olympic lake'],
    location: 'San Francisco, California',
    architect: 'Sam Whiting',
    logo: '🏛️',
    logoUrl: '',
  },
  {
    id: 'san-francisco-gc',
    name: 'San Francisco Golf Club',
    shortName: 'San Francisco GC',
    aliases: ['sfgc', 'san francisco golf club'],
    location: 'San Francisco, California',
    architect: 'A.W. Tillinghast',
    logo: '🌉',
    logoUrl: '',
  },
  {
    id: 'baltusrol-lower',
    name: 'Baltusrol Golf Club (Lower)',
    shortName: 'Baltusrol Lower',
    aliases: ['baltusrol', 'baltusrol gc', 'baltusrol lower course'],
    location: 'Springfield, New Jersey',
    architect: 'A.W. Tillinghast',
    logo: '⛳',
    logoUrl: '',
  },
  {
    id: 'bethpage-black',
    name: 'Bethpage State Park (Black)',
    shortName: 'Bethpage Black',
    aliases: ['bethpage', 'the black', 'bethpage black course'],
    location: 'Farmingdale, New York',
    architect: 'A.W. Tillinghast',
    logo: '⚫',
    logoUrl: '',
  },
  {
    id: 'pinehurst-no-2',
    name: 'Pinehurst No. 2',
    shortName: 'Pinehurst No. 2',
    aliases: ['pinehurst 2', 'pinehurst', 'pinehurst number 2', 'pinehurst #2'],
    location: 'Pinehurst, North Carolina',
    architect: 'Donald Ross',
    logo: '🌲',
    logoUrl: '',
  },
  {
    id: 'whistling-straits',
    name: 'Whistling Straits (Straits)',
    shortName: 'Whistling Straits',
    aliases: ['whistling straits straits', 'the straits', 'whistling straits gc'],
    location: 'Haven, Wisconsin',
    architect: 'Pete Dye',
    logo: '🌬️',
    logoUrl: '',
  },
  {
    id: 'erin-hills',
    name: 'Erin Hills',
    shortName: 'Erin Hills',
    aliases: ['erin hills gc'],
    location: 'Erin, Wisconsin',
    architect: 'Hurdzan, Fry & Whitten',
    logo: '🌾',
    logoUrl: '',
  },
  {
    id: 'tpc-sawgrass',
    name: 'TPC Sawgrass (Stadium)',
    shortName: 'TPC Sawgrass',
    aliases: ['sawgrass', 'players stadium course', 'tpc sawgrass stadium'],
    location: 'Ponte Vedra Beach, Florida',
    architect: 'Pete Dye',
    logo: '🏝️',
    logoUrl: '',
  },
  {
    id: 'kiawah-ocean',
    name: 'Kiawah Island Golf Resort (Ocean)',
    shortName: 'Kiawah Ocean Course',
    aliases: ['kiawah', 'the ocean course', 'kiawah ocean'],
    location: 'Kiawah Island, South Carolina',
    architect: 'Pete Dye',
    logo: '🌊',
    logoUrl: '',
  },
  {
    id: 'harbour-town',
    name: 'Harbour Town Golf Links',
    shortName: 'Harbour Town',
    aliases: ['harbour town gl', 'sea pines harbour town'],
    location: 'Hilton Head, South Carolina',
    architect: 'Pete Dye & Jack Nicklaus',
    logo: '🚤',
    logoUrl: '',
  },
  {
    id: 'tobacco-road',
    name: 'Tobacco Road Golf Club',
    shortName: 'Tobacco Road',
    aliases: ['tobacco road gc'],
    location: 'Sanford, North Carolina',
    architect: 'Mike Strantz',
    logo: '🚬',
    logoUrl: '',
  },
  {
    id: 'streamsong-blue',
    name: 'Streamsong Resort',
    shortName: 'Streamsong',
    // Consolidated from 3 courses (Red, Blue, Black) — same resort, same
    // logo. ID kept as streamsong-blue so the existing logo asset filename
    // does not need to move.
    aliases: ['streamsong', 'streamsong red', 'streamsong blue', 'streamsong black'],
    location: 'Bowling Green, Florida',
    architect: 'Coore & Crenshaw / Tom Doak / Gil Hanse',
    logo: '🏖️',
    logoUrl: '',
  },
  {
    id: 'cabot-citrus-farms',
    name: 'Cabot Citrus Farms',
    shortName: 'Cabot Citrus Farms',
    aliases: ['cabot citrus', 'world woods', 'pine barrens cabot'],
    location: 'Brooksville, Florida',
    architect: 'Kyle Franz / Mike Strantz',
    logo: '🍊',
    logoUrl: '',
  },
  {
    id: 'inverness',
    name: 'Inverness Club',
    shortName: 'Inverness',
    aliases: ['inverness club'],
    location: 'Toledo, Ohio',
    architect: 'Donald Ross',
    logo: '⛳',
    logoUrl: '',
  },
  {
    id: 'crystal-downs',
    name: 'Crystal Downs Country Club',
    shortName: 'Crystal Downs',
    aliases: ['crystal downs cc'],
    location: 'Frankfort, Michigan',
    architect: 'Alister MacKenzie & Perry Maxwell',
    logo: '💎',
    logoUrl: '',
  },
  {
    id: 'prairie-dunes',
    name: 'Prairie Dunes Country Club',
    shortName: 'Prairie Dunes',
    aliases: ['prairie dunes cc'],
    location: 'Hutchinson, Kansas',
    architect: 'Perry Maxwell',
    logo: '🌾',
    logoUrl: '',
  },
  {
    id: 'oak-hill-east',
    name: 'Oak Hill Country Club (East)',
    shortName: 'Oak Hill East',
    aliases: ['oak hill', 'oak hill cc'],
    location: 'Rochester, New York',
    architect: 'Donald Ross',
    logo: '🌳',
    logoUrl: '',
  },
  {
    id: 'medinah-3',
    name: 'Medinah Country Club (No. 3)',
    shortName: 'Medinah No. 3',
    aliases: ['medinah', 'medinah cc', 'medinah 3'],
    location: 'Medinah, Illinois',
    architect: 'Tom Bendelow',
    logo: '🕌',
    logoUrl: '',
  },
  {
    id: 'quaker-ridge',
    name: 'Quaker Ridge Golf Club',
    shortName: 'Quaker Ridge',
    aliases: ['quaker ridge gc'],
    location: 'Scarsdale, New York',
    architect: 'A.W. Tillinghast',
    logo: '🎩',
    logoUrl: '',
  },
  {
    id: 'wade-hampton',
    name: 'Wade Hampton Golf Club',
    shortName: 'Wade Hampton',
    aliases: ['wade hampton gc'],
    location: 'Cashiers, North Carolina',
    architect: 'Tom Fazio',
    logo: '⛰️',
    logoUrl: '',
  },
  {
    id: 'east-lake',
    name: 'East Lake Golf Club',
    shortName: 'East Lake',
    aliases: ['east lake gc', 'tour championship'],
    location: 'Atlanta, Georgia',
    architect: 'Donald Ross / Rees Jones',
    logo: '🏆',
    logoUrl: '',
  },
  {
    id: 'whispering-pines',
    name: 'Whispering Pines Golf Club',
    shortName: 'Whispering Pines',
    aliases: ['whispering pines gc'],
    location: 'Trinity, Texas',
    architect: 'Chet Williams',
    logo: '🌲',
    logoUrl: '',
  },
  {
    id: 'castle-pines',
    name: 'Castle Pines Golf Club',
    shortName: 'Castle Pines',
    aliases: ['castle pines gc'],
    location: 'Castle Rock, Colorado',
    architect: 'Jack Nicklaus',
    logo: '🏰',
    logoUrl: '',
  },
  {
    id: 'shadow-creek',
    name: 'Shadow Creek',
    shortName: 'Shadow Creek',
    aliases: ['shadow creek gc'],
    location: 'North Las Vegas, Nevada',
    architect: 'Tom Fazio',
    logo: '🌑',
    logoUrl: '',
  },
  {
    id: 'friars-head',
    name: "Friar's Head",
    shortName: "Friar's Head",
    aliases: ['friars head', 'friars head gc'],
    location: 'Baiting Hollow, New York',
    architect: 'Bill Coore & Ben Crenshaw',
    logo: '⛪',
    logoUrl: '',
  },
  {
    id: 'somerset-hills',
    name: 'Somerset Hills Country Club',
    shortName: 'Somerset Hills',
    aliases: ['somerset hills cc'],
    location: 'Bernardsville, New Jersey',
    architect: 'A.W. Tillinghast',
    logo: '🏞️',
    logoUrl: '',
  },
  {
    id: 'maidstone',
    name: 'Maidstone Club',
    shortName: 'Maidstone',
    aliases: ['maidstone club'],
    location: 'East Hampton, New York',
    architect: 'Willie & John Park Jr.',
    logo: '🏖️',
    logoUrl: '',
  },

  // ── Scotland ─────────────────────────────────────────────────────────────
  {
    id: 'st-andrews-old',
    name: 'The Old Course at St Andrews',
    shortName: 'St Andrews (Old)',
    aliases: ['st andrews', 'old course', 'the old course', 'st andrews old course', 'home of golf'],
    location: 'St Andrews, Scotland',
    architect: 'Old Tom Morris (evolved)',
    logo: '🏰',
    logoUrl: '',
  },
  {
    id: 'muirfield',
    name: 'Muirfield (The Honourable Company of Edinburgh Golfers)',
    shortName: 'Muirfield',
    aliases: ['muirfield gc', 'honourable company of edinburgh golfers', 'the honourable company'],
    location: 'Gullane, Scotland',
    architect: 'Old Tom Morris / Harry Colt',
    logo: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    logoUrl: '',
  },
  {
    id: 'royal-dornoch',
    name: 'Royal Dornoch Golf Club (Championship)',
    shortName: 'Royal Dornoch',
    aliases: ['dornoch', 'royal dornoch gc'],
    location: 'Dornoch, Scotland',
    architect: 'Old Tom Morris / John Sutherland',
    logo: '👑',
    logoUrl: '',
  },
  {
    id: 'turnberry-ailsa',
    name: 'Trump Turnberry (Ailsa)',
    shortName: 'Turnberry (Ailsa)',
    aliases: ['turnberry', 'ailsa', 'trump turnberry', 'turnberry ailsa course'],
    location: 'Turnberry, Scotland',
    architect: 'Mackenzie Ross',
    logo: '🗼',
    logoUrl: '',
  },
  {
    id: 'carnoustie',
    name: 'Carnoustie Golf Links (Championship)',
    shortName: 'Carnoustie',
    aliases: ['carnoustie championship', 'car-nasty', 'carnoustie gl'],
    location: 'Carnoustie, Scotland',
    architect: 'James Braid',
    logo: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    logoUrl: '',
  },
  {
    id: 'north-berwick',
    name: 'North Berwick (West Links)',
    shortName: 'North Berwick',
    aliases: ['north berwick west', 'north berwick gc', 'west links'],
    location: 'North Berwick, Scotland',
    architect: '—',
    logo: '🪨',
    logoUrl: '',
  },
  {
    id: 'kingsbarns',
    name: 'Kingsbarns Golf Links',
    shortName: 'Kingsbarns',
    aliases: ['kingsbarns gl'],
    location: 'St Andrews, Scotland',
    architect: 'Kyle Phillips',
    logo: '🌊',
    logoUrl: '',
  },
  {
    id: 'cruden-bay',
    name: 'Cruden Bay Golf Club',
    shortName: 'Cruden Bay',
    aliases: ['cruden bay gc'],
    location: 'Cruden Bay, Scotland',
    architect: 'Old Tom Morris / Tom Simpson',
    logo: '🌅',
    logoUrl: '',
  },
  {
    id: 'machrihanish',
    name: 'Machrihanish Golf Club',
    shortName: 'Machrihanish',
    aliases: ['machrihanish gc', 'old mach'],
    location: 'Campbeltown, Scotland',
    architect: 'Old Tom Morris',
    logo: '🪶',
    logoUrl: '',
  },
  {
    id: 'machrihanish-dunes',
    name: 'Machrihanish Dunes',
    shortName: 'Machrihanish Dunes',
    aliases: ['mach dunes'],
    location: 'Campbeltown, Scotland',
    architect: 'David McLay Kidd',
    logo: '🏞️',
    logoUrl: '',
  },
  {
    id: 'castle-stuart',
    name: 'Castle Stuart Golf Links',
    shortName: 'Castle Stuart',
    aliases: ['castle stuart gl'],
    location: 'Inverness, Scotland',
    architect: 'Gil Hanse & Mark Parsinen',
    logo: '🏰',
    logoUrl: '',
  },
  {
    id: 'royal-troon',
    name: 'Royal Troon Golf Club (Old)',
    shortName: 'Royal Troon',
    aliases: ['troon', 'royal troon gc', 'royal troon old'],
    location: 'Troon, Scotland',
    architect: 'Willie Fernie',
    logo: '👑',
    logoUrl: '',
  },

  // ── England, Wales, Northern Ireland & Ireland ───────────────────────────
  {
    id: 'royal-county-down',
    name: 'Royal County Down Golf Club (Championship)',
    shortName: 'Royal County Down',
    aliases: ['rcd', 'royal county down gc', 'county down'],
    location: 'Newcastle, Northern Ireland',
    architect: 'Old Tom Morris / Harry Vardon',
    logo: '⛰️',
    logoUrl: '',
  },
  {
    id: 'royal-portrush-dunluce',
    name: 'Royal Portrush Golf Club (Dunluce)',
    shortName: 'Royal Portrush',
    aliases: ['portrush', 'royal portrush dunluce', 'dunluce'],
    location: 'Portrush, Northern Ireland',
    architect: 'Harry Colt',
    logo: '🏰',
    logoUrl: '',
  },
  {
    id: 'ballybunion-old',
    name: 'Ballybunion Golf Club (Old)',
    shortName: 'Ballybunion (Old)',
    aliases: ['ballybunion', 'ballybunion old course'],
    location: 'Ballybunion, Ireland',
    architect: 'Tom Simpson (revisions)',
    logo: '🍀',
    logoUrl: '',
  },
  {
    id: 'lahinch',
    name: 'Lahinch Golf Club',
    shortName: 'Lahinch',
    aliases: ['lahinch gc', 'old course lahinch'],
    location: 'Lahinch, Ireland',
    architect: 'Old Tom Morris / Alister MacKenzie',
    logo: '🐐',
    logoUrl: '',
  },
  {
    id: 'portmarnock',
    name: 'Portmarnock Golf Club',
    shortName: 'Portmarnock',
    aliases: ['portmarnock gc'],
    location: 'Portmarnock, Ireland',
    architect: 'W.C. Pickeman / Mungo Park',
    logo: '☘️',
    logoUrl: '',
  },
  {
    id: 'european-club',
    name: 'The European Club',
    shortName: 'European Club',
    aliases: ['european club ireland'],
    location: 'Brittas Bay, Ireland',
    architect: 'Pat Ruddy',
    logo: '🇪🇺',
    logoUrl: '',
  },
  {
    id: 'royal-st-georges',
    name: "Royal St George's Golf Club",
    shortName: "Royal St George's",
    aliases: ['royal st georges', 'sandwich', 'rsg'],
    location: 'Sandwich, England',
    architect: 'William Laidlaw Purves',
    logo: '🐉',
    logoUrl: '',
  },
  {
    id: 'sunningdale-old',
    name: 'Sunningdale Golf Club (Old)',
    shortName: 'Sunningdale Old',
    aliases: ['sunningdale', 'sunningdale gc', 'sunningdale old course'],
    location: 'Sunningdale, England',
    architect: 'Willie Park Jr.',
    logo: '☀️',
    logoUrl: '',
  },
  {
    id: 'royal-birkdale',
    name: 'Royal Birkdale Golf Club',
    shortName: 'Royal Birkdale',
    aliases: ['birkdale', 'royal birkdale gc'],
    location: 'Southport, England',
    architect: 'George Lowe / F.G. Hawtree',
    logo: '🌾',
    logoUrl: '',
  },
  {
    id: 'royal-lytham',
    name: "Royal Lytham & St Annes Golf Club",
    shortName: "Royal Lytham",
    aliases: ['royal lytham and st annes', 'lytham', 'royal lytham gc'],
    location: 'Lytham St Annes, England',
    architect: 'George Lowe',
    logo: '⛳',
    logoUrl: '',
  },
  {
    id: 'royal-liverpool',
    name: 'Royal Liverpool Golf Club',
    shortName: 'Royal Liverpool',
    aliases: ['hoylake', 'royal liverpool gc'],
    location: 'Hoylake, England',
    architect: 'Robert Chambers / George Morris',
    logo: '🐦',
    logoUrl: '',
  },
  {
    id: 'swinley-forest',
    name: 'Swinley Forest Golf Club',
    shortName: 'Swinley Forest',
    aliases: ['swinley', 'swinley forest gc'],
    location: 'Ascot, England',
    architect: 'Harry Colt',
    logo: '🌲',
    logoUrl: '',
  },
  {
    id: 'walton-heath-old',
    name: 'Walton Heath Golf Club (Old)',
    shortName: 'Walton Heath',
    aliases: ['walton heath', 'walton heath old course', 'walton heath gc'],
    location: 'Walton-on-the-Hill, England',
    architect: 'Herbert Fowler',
    logo: '🌿',
    logoUrl: '',
  },

  // ── Continental Europe ───────────────────────────────────────────────────
  {
    id: 'morfontaine',
    name: 'Golf de Morfontaine',
    shortName: 'Morfontaine',
    aliases: ['morfontaine gc'],
    location: 'Mortefontaine, France',
    architect: 'Tom Simpson',
    logo: '🥖',
    logoUrl: '',
  },
  {
    id: 'les-bordes',
    name: 'Les Bordes Golf Club',
    shortName: 'Les Bordes',
    aliases: ['les bordes gc'],
    location: 'Saint-Laurent-Nouan, France',
    architect: 'Robert von Hagge',
    logo: '🍇',
    logoUrl: '',
  },
  {
    id: 'valderrama',
    name: 'Real Club Valderrama',
    shortName: 'Valderrama',
    aliases: ['valderrama gc', 'rc valderrama'],
    location: 'Sotogrande, Spain',
    architect: 'Robert Trent Jones Sr.',
    logo: '🫒',
    logoUrl: '',
  },

  // ── Australia & New Zealand ──────────────────────────────────────────────
  {
    id: 'royal-melbourne-west',
    name: 'Royal Melbourne Golf Club (West)',
    shortName: 'Royal Melbourne (West)',
    aliases: ['royal melbourne', 'royal melbourne gc', 'rmgc', 'royal melbourne west course'],
    location: 'Black Rock, Australia',
    architect: 'Alister MacKenzie',
    logo: '🦘',
    logoUrl: '',
  },
  {
    id: 'kingston-heath',
    name: 'Kingston Heath Golf Club',
    shortName: 'Kingston Heath',
    aliases: ['kingston heath gc'],
    location: 'Cheltenham, Australia',
    architect: 'Dan Soutar / Alister MacKenzie',
    logo: '🌿',
    logoUrl: '',
  },
  {
    id: 'barnbougle-dunes',
    name: 'Barnbougle Dunes',
    shortName: 'Barnbougle Dunes',
    aliases: ['barnbougle'],
    location: 'Bridport, Tasmania, Australia',
    architect: 'Tom Doak & Mike Clayton',
    logo: '🌊',
    logoUrl: '',
  },
  {
    id: 'barnbougle-lost-farm',
    name: 'Barnbougle Lost Farm',
    shortName: 'Lost Farm',
    aliases: ['barnbougle lost farm', 'lost farm'],
    location: 'Bridport, Tasmania, Australia',
    architect: 'Bill Coore & Ben Crenshaw',
    logo: '🚜',
    logoUrl: '',
  },
  {
    id: 'cape-wickham',
    name: 'Cape Wickham Links',
    shortName: 'Cape Wickham',
    aliases: ['cape wickham links'],
    location: 'King Island, Australia',
    architect: 'Mike DeVries & Darius Oliver',
    logo: '🌬️',
    logoUrl: '',
  },
  {
    id: 'new-south-wales',
    name: 'New South Wales Golf Club',
    shortName: 'New South Wales',
    aliases: ['nsw gc', 'new south wales gc'],
    location: 'La Perouse, Australia',
    architect: 'Alister MacKenzie',
    logo: '🌊',
    logoUrl: '',
  },
  {
    id: 'tara-iti',
    name: 'Tara Iti Golf Club',
    shortName: 'Tara Iti',
    aliases: ['tara iti gc'],
    location: 'Te Arai, New Zealand',
    architect: 'Tom Doak',
    logo: '🐦',
    logoUrl: '',
  },
  {
    id: 'cape-kidnappers',
    name: 'Cape Kidnappers',
    shortName: 'Cape Kidnappers',
    aliases: ['cape kidnappers gc', 'kidnappers'],
    location: "Hawke's Bay, New Zealand",
    architect: 'Tom Doak',
    logo: '🌊',
    logoUrl: '',
  },

  // ── Canada & Caribbean ───────────────────────────────────────────────────
  {
    id: 'cabot-cliffs',
    name: 'Cabot Cliffs',
    shortName: 'Cabot Cliffs',
    aliases: ['cabot cliffs gc'],
    location: 'Inverness, Nova Scotia, Canada',
    architect: 'Bill Coore & Ben Crenshaw',
    logo: '🧗',
    logoUrl: '',
  },
  {
    id: 'cabot-links',
    name: 'Cabot Links',
    shortName: 'Cabot Links',
    aliases: ['cabot', 'cabot links gc'],
    location: 'Inverness, Nova Scotia, Canada',
    architect: 'Rod Whitman',
    logo: '🍁',
    logoUrl: '',
  },
  {
    id: 'st-georges-canada',
    name: "St. George's Golf and Country Club",
    shortName: "St. George's (Canada)",
    aliases: ['st georges canada', 'st georges gc canada'],
    location: 'Etobicoke, Ontario, Canada',
    architect: 'Stanley Thompson',
    logo: '🍁',
    logoUrl: '',
  },
  {
    id: 'hamilton-gcc',
    name: 'Hamilton Golf and Country Club',
    shortName: 'Hamilton G&CC',
    aliases: ['hamilton golf and country club', 'hamilton gcc'],
    location: 'Ancaster, Ontario, Canada',
    architect: 'Harry Colt',
    logo: '🍁',
    logoUrl: '',
  },

  // ── Asia ─────────────────────────────────────────────────────────────────
  {
    id: 'hirono',
    name: 'Hirono Golf Club',
    shortName: 'Hirono',
    aliases: ['hirono gc'],
    location: 'Kobe, Japan',
    architect: 'Charles Alison',
    logo: '🌸',
    logoUrl: '',
  },
  {
    id: 'kawana-fuji',
    name: 'Kawana Hotel (Fuji)',
    shortName: 'Kawana (Fuji)',
    aliases: ['kawana', 'kawana fuji course', 'kawana hotel fuji'],
    location: 'Itō, Japan',
    architect: 'Charles Alison',
    logo: '🗻',
    logoUrl: '',
  },
  {
    id: 'tokyo-gc',
    name: 'Tokyo Golf Club',
    shortName: 'Tokyo Golf Club',
    aliases: ['tokyo gc'],
    location: 'Sayama, Japan',
    architect: 'Komyo Otani',
    logo: '🗾',
    logoUrl: '',
  },

  // ── Additional United States (public, municipal, resort, modern) ─────────
  {
    id: 'chambers-bay',
    name: 'Chambers Bay',
    shortName: 'Chambers Bay',
    aliases: ['chambers bay golf course'],
    location: 'University Place, Washington',
    architect: 'Robert Trent Jones Jr.',
    logo: '🌊',
    logoUrl: '',
  },
  {
    id: 'black-mesa',
    name: 'Black Mesa Golf Club',
    shortName: 'Black Mesa',
    aliases: ['black mesa gc'],
    location: 'La Mesilla, New Mexico',
    architect: 'Baxter Spann',
    logo: '🏜️',
    logoUrl: '',
  },
  {
    id: 'wolf-creek',
    name: 'Wolf Creek Golf Club',
    shortName: 'Wolf Creek',
    aliases: ['wolf creek gc', 'wolf creek mesquite'],
    location: 'Mesquite, Nevada',
    architect: 'Dennis Rider',
    logo: '🐺',
    logoUrl: '',
  },
  {
    id: 'bayonne',
    name: 'Bayonne Golf Club',
    shortName: 'Bayonne',
    aliases: ['bayonne gc'],
    location: 'Bayonne, New Jersey',
    architect: 'Eric Bergstol',
    logo: '🌊',
    logoUrl: '',
  },
  {
    id: 'old-sandwich',
    name: 'Old Sandwich Golf Club',
    shortName: 'Old Sandwich',
    aliases: ['old sandwich gc'],
    location: 'Plymouth, Massachusetts',
    architect: 'Bill Coore & Ben Crenshaw',
    logo: '🌾',
    logoUrl: '',
  },
  {
    id: 'quail-hollow',
    name: 'Quail Hollow Club',
    shortName: 'Quail Hollow',
    aliases: ['quail hollow cc', 'wells fargo championship'],
    location: 'Charlotte, North Carolina',
    architect: 'George Cobb / Tom Fazio',
    logo: '🐦',
    logoUrl: '',
  },
  {
    id: 'wild-horse',
    name: 'Wild Horse Golf Club',
    shortName: 'Wild Horse',
    aliases: ['wild horse gc'],
    location: 'Gothenburg, Nebraska',
    architect: 'Dave Axland & Dan Proctor',
    logo: '🐴',
    logoUrl: '',
  },
  {
    id: 'yeamans-hall',
    name: 'Yeamans Hall Club',
    shortName: 'Yeamans Hall',
    aliases: ['yeamans hall club'],
    location: 'Hanahan, South Carolina',
    architect: 'Seth Raynor',
    logo: '🌳',
    logoUrl: '',
  },
  {
    id: 'camargo-club',
    name: 'The Camargo Club',
    shortName: 'Camargo',
    aliases: ['camargo club'],
    location: 'Indian Hill, Ohio',
    architect: 'Seth Raynor',
    logo: '⛳',
    logoUrl: '',
  },
  {
    id: 'old-town-club',
    name: 'Old Town Club',
    shortName: 'Old Town',
    aliases: ['old town club nc'],
    location: 'Winston-Salem, North Carolina',
    architect: 'Perry Maxwell',
    logo: '🌳',
    logoUrl: '',
  },
  {
    id: 'sleepy-hollow',
    name: 'Sleepy Hollow Country Club',
    shortName: 'Sleepy Hollow',
    aliases: ['sleepy hollow cc'],
    location: 'Briarcliff Manor, New York',
    architect: 'C.B. Macdonald & Seth Raynor',
    logo: '🎃',
    logoUrl: '',
  },
  {
    id: 'garden-city',
    name: 'Garden City Golf Club',
    shortName: 'Garden City',
    aliases: ['garden city gc'],
    location: 'Garden City, New York',
    architect: 'Devereux Emmet / Walter Travis',
    logo: '🌷',
    logoUrl: '',
  },
  {
    id: 'tpc-scottsdale',
    name: 'TPC Scottsdale (Stadium)',
    shortName: 'TPC Scottsdale',
    aliases: ['tpc scottsdale stadium', 'waste management open', 'phoenix open'],
    location: 'Scottsdale, Arizona',
    architect: 'Tom Weiskopf & Jay Morrish',
    logo: '🌵',
    logoUrl: '',
  },
  {
    id: 'tpc-river-highlands',
    name: 'TPC River Highlands',
    shortName: 'TPC River Highlands',
    aliases: ['river highlands', 'travelers championship'],
    location: 'Cromwell, Connecticut',
    architect: 'Pete Dye / Bobby Weed',
    logo: '🏞️',
    logoUrl: '',
  },
  {
    id: 'detroit-golf-club',
    name: 'Detroit Golf Club',
    shortName: 'Detroit Golf Club',
    aliases: ['detroit gc', 'rocket mortgage classic'],
    location: 'Detroit, Michigan',
    architect: 'Donald Ross',
    logo: '🏛️',
    logoUrl: '',
  },
  {
    id: 'colonial',
    name: 'Colonial Country Club',
    shortName: 'Colonial',
    aliases: ['colonial cc', 'charles schwab challenge'],
    location: 'Fort Worth, Texas',
    architect: 'John Bredemus / Perry Maxwell',
    logo: '🤠',
    logoUrl: '',
  },
  {
    id: 'muirfield-village',
    name: 'Muirfield Village Golf Club',
    shortName: 'Muirfield Village',
    aliases: ['memorial tournament', 'muirfield village gc'],
    location: 'Dublin, Ohio',
    architect: 'Jack Nicklaus & Desmond Muirhead',
    logo: '🏆',
    logoUrl: '',
  },
  {
    id: 'sand-valley',
    name: 'Sand Valley',
    shortName: 'Sand Valley',
    aliases: ['sand valley resort'],
    location: 'Nekoosa, Wisconsin',
    architect: 'Bill Coore & Ben Crenshaw',
    logo: '🏖️',
    logoUrl: '',
  },
  {
    id: 'mammoth-dunes',
    name: 'Mammoth Dunes',
    shortName: 'Mammoth Dunes',
    aliases: ['sand valley mammoth dunes'],
    location: 'Nekoosa, Wisconsin',
    architect: 'David McLay Kidd',
    logo: '🦣',
    logoUrl: '',
  },
  {
    id: 'sedge-valley',
    name: 'Sedge Valley',
    shortName: 'Sedge Valley',
    aliases: ['sand valley sedge valley'],
    location: 'Nekoosa, Wisconsin',
    architect: 'Tom Doak',
    logo: '🌾',
    logoUrl: '',
  },
  {
    id: 'forest-dunes',
    name: 'Forest Dunes Golf Club',
    shortName: 'Forest Dunes',
    aliases: ['forest dunes gc'],
    location: 'Roscommon, Michigan',
    architect: 'Tom Weiskopf',
    logo: '🌲',
    logoUrl: '',
  },
  {
    id: 'the-loop',
    name: 'The Loop at Forest Dunes',
    shortName: 'The Loop',
    aliases: ['the loop forest dunes', 'reversible loop'],
    location: 'Roscommon, Michigan',
    architect: 'Tom Doak',
    logo: '🔁',
    logoUrl: '',
  },
  {
    id: 'arcadia-bluffs',
    name: 'Arcadia Bluffs Golf Club',
    shortName: 'Arcadia Bluffs',
    aliases: ['arcadia bluffs gc'],
    location: 'Arcadia, Michigan',
    architect: 'Rick Smith & Warren Henderson',
    logo: '🌊',
    logoUrl: '',
  },
  {
    id: 'spyglass-hill',
    name: 'Spyglass Hill Golf Course',
    shortName: 'Spyglass Hill',
    aliases: ['spyglass', 'spyglass hill gc'],
    location: 'Pebble Beach, California',
    architect: 'Robert Trent Jones Sr.',
    logo: '🔭',
    logoUrl: '',
  },
  {
    id: 'monterey-peninsula-shore',
    name: 'Monterey Peninsula Country Club (Shore)',
    shortName: 'MPCC Shore',
    aliases: ['mpcc shore', 'monterey peninsula cc shore'],
    location: 'Pebble Beach, California',
    architect: 'Mike Strantz',
    logo: '🌊',
    logoUrl: '',
  },
  {
    id: 'pasatiempo',
    name: 'Pasatiempo Golf Club',
    shortName: 'Pasatiempo',
    aliases: ['pasatiempo gc'],
    location: 'Santa Cruz, California',
    architect: 'Alister MacKenzie',
    logo: '🏄',
    logoUrl: '',
  },
  {
    id: 'congressional-blue',
    name: 'Congressional Country Club (Blue)',
    shortName: 'Congressional',
    aliases: ['congressional cc', 'congressional blue'],
    location: 'Bethesda, Maryland',
    architect: 'Devereux Emmet / Rees Jones',
    logo: '🏛️',
    logoUrl: '',
  },
  {
    id: 'plainfield',
    name: 'Plainfield Country Club',
    shortName: 'Plainfield',
    aliases: ['plainfield cc'],
    location: 'Edison, New Jersey',
    architect: 'Donald Ross',
    logo: '🌳',
    logoUrl: '',
  },
  {
    id: 'aronimink',
    name: 'Aronimink Golf Club',
    shortName: 'Aronimink',
    aliases: ['aronimink gc'],
    location: 'Newtown Square, Pennsylvania',
    architect: 'Donald Ross',
    logo: '🌳',
    logoUrl: '',
  },
  {
    id: 'cherry-hills',
    name: 'Cherry Hills Country Club',
    shortName: 'Cherry Hills',
    aliases: ['cherry hills cc'],
    location: 'Cherry Hills Village, Colorado',
    architect: 'William Flynn',
    logo: '🍒',
    logoUrl: '',
  },
  {
    id: 'southern-hills',
    name: 'Southern Hills Country Club',
    shortName: 'Southern Hills',
    aliases: ['southern hills cc'],
    location: 'Tulsa, Oklahoma',
    architect: 'Perry Maxwell',
    logo: '⛳',
    logoUrl: '',
  },
  {
    id: 'firestone-south',
    name: 'Firestone Country Club (South)',
    shortName: 'Firestone South',
    aliases: ['firestone cc', 'firestone south course'],
    location: 'Akron, Ohio',
    architect: 'Robert Trent Jones Sr.',
    logo: '🔥',
    logoUrl: '',
  },
  {
    id: 'olympia-fields-north',
    name: 'Olympia Fields Country Club (North)',
    shortName: 'Olympia Fields North',
    aliases: ['olympia fields', 'olympia fields cc'],
    location: 'Olympia Fields, Illinois',
    architect: 'Willie Park Jr.',
    logo: '🏛️',
    logoUrl: '',
  },
  {
    id: 'tpc-southwind',
    name: 'TPC Southwind',
    shortName: 'TPC Southwind',
    aliases: ['southwind', 'fedex st jude'],
    location: 'Memphis, Tennessee',
    architect: 'Ron Pritchard',
    logo: '🎷',
    logoUrl: '',
  },
  {
    id: 'austin-cc',
    name: 'Austin Country Club',
    shortName: 'Austin CC',
    aliases: ['austin country club', 'wgc match play'],
    location: 'Austin, Texas',
    architect: 'Pete Dye',
    logo: '🎸',
    logoUrl: '',
  },
  {
    id: 'wolf-point',
    name: 'Wolf Point Club',
    shortName: 'Wolf Point',
    aliases: ['wolf point club texas'],
    location: 'Port Lavaca, Texas',
    architect: 'Mike Nuzzo',
    logo: '🐺',
    logoUrl: '',
  },
  {
    id: 'ohoopee-match',
    name: 'Ohoopee Match Club',
    shortName: 'Ohoopee',
    aliases: ['ohoopee match club'],
    location: 'Cobbtown, Georgia',
    architect: 'Gil Hanse',
    logo: '⛳',
    logoUrl: '',
  },
  {
    id: 'gozzer-ranch',
    name: 'Gozzer Ranch Golf and Lake Club',
    shortName: 'Gozzer Ranch',
    aliases: ['gozzer ranch'],
    location: 'Harrison, Idaho',
    architect: 'Tom Fazio',
    logo: '🦌',
    logoUrl: '',
  },
  {
    id: 'congaree',
    name: 'Congaree Golf Club',
    shortName: 'Congaree',
    aliases: ['congaree gc'],
    location: 'Ridgeland, South Carolina',
    architect: 'Tom Fazio',
    logo: '🌲',
    logoUrl: '',
  },

  // ── Additional Scotland / England / Ireland ──────────────────────────────
  {
    id: 'royal-porthcawl',
    name: 'Royal Porthcawl Golf Club',
    shortName: 'Royal Porthcawl',
    aliases: ['royal porthcawl gc', 'porthcawl'],
    location: 'Porthcawl, Wales',
    architect: 'Charles Gibson / Harry Colt',
    logo: '🏴',
    logoUrl: '',
  },
  {
    id: 'royal-ashdown-forest',
    name: 'Royal Ashdown Forest Golf Club',
    shortName: 'Royal Ashdown',
    aliases: ['royal ashdown', 'royal ashdown forest gc'],
    location: 'Forest Row, England',
    architect: 'Reverend A.T. Scott',
    logo: '🌳',
    logoUrl: '',
  },
  {
    id: 'rye',
    name: 'Rye Golf Club',
    shortName: 'Rye',
    aliases: ['rye gc'],
    location: 'Rye, England',
    architect: 'Harry Colt',
    logo: '🌾',
    logoUrl: '',
  },
  {
    id: 'st-georges-hill',
    name: "St George's Hill Golf Club",
    shortName: "St George's Hill",
    aliases: ['st georges hill', 'st georges hill gc'],
    location: 'Weybridge, England',
    architect: 'Harry Colt',
    logo: '🐉',
    logoUrl: '',
  },
  {
    id: 'royal-cinque-ports',
    name: 'Royal Cinque Ports Golf Club',
    shortName: 'Royal Cinque Ports',
    aliases: ['deal', 'royal cinque ports gc'],
    location: 'Deal, England',
    architect: 'Tom Dunn / James Braid',
    logo: '⛳',
    logoUrl: '',
  },
  {
    id: 'royal-west-norfolk',
    name: 'Royal West Norfolk Golf Club',
    shortName: 'Brancaster',
    aliases: ['brancaster', 'royal west norfolk', 'rwn gc'],
    location: 'Brancaster, England',
    architect: 'Holcombe Ingleby',
    logo: '🪶',
    logoUrl: '',
  },
  {
    id: 'royal-aberdeen',
    name: 'Royal Aberdeen Golf Club',
    shortName: 'Royal Aberdeen',
    aliases: ['royal aberdeen gc', 'balgownie'],
    location: 'Aberdeen, Scotland',
    architect: 'Robert Simpson',
    logo: '👑',
    logoUrl: '',
  },
  {
    id: 'trump-international-scotland',
    name: 'Trump International Golf Links Scotland',
    shortName: 'Trump Aberdeen',
    aliases: ['trump aberdeen', 'menie', 'trump international scotland'],
    location: 'Balmedie, Scotland',
    architect: 'Martin Hawtree',
    logo: '🌬️',
    logoUrl: '',
  },
  {
    id: 'gleneagles-kings',
    name: "Gleneagles (King's)",
    shortName: "Gleneagles King's",
    aliases: ['gleneagles', 'gleneagles kings', 'kings course gleneagles'],
    location: 'Auchterarder, Scotland',
    architect: 'James Braid',
    logo: '🏰',
    logoUrl: '',
  },
  {
    id: 'gleneagles-pga-centenary',
    name: 'Gleneagles (PGA Centenary)',
    shortName: 'PGA Centenary',
    aliases: ['gleneagles pga centenary', 'centenary course'],
    location: 'Auchterarder, Scotland',
    architect: 'Jack Nicklaus',
    logo: '🏆',
    logoUrl: '',
  },
  {
    id: 'prestwick',
    name: 'Prestwick Golf Club',
    shortName: 'Prestwick',
    aliases: ['prestwick gc'],
    location: 'Prestwick, Scotland',
    architect: 'Old Tom Morris',
    logo: '⛳',
    logoUrl: '',
  },
  {
    id: 'royal-st-davids',
    name: "Royal St David's Golf Club",
    shortName: "Royal St David's",
    aliases: ['royal st davids', 'harlech'],
    location: 'Harlech, Wales',
    architect: 'Harold Finch-Hatton',
    logo: '🐉',
    logoUrl: '',
  },
  {
    id: 'old-head',
    name: 'Old Head Golf Links',
    shortName: 'Old Head',
    aliases: ['old head kinsale', 'old head gl'],
    location: 'Kinsale, Ireland',
    architect: 'Ron Kirby / Joe Carr / Eddie Hackett',
    logo: '🏔️',
    logoUrl: '',
  },
  {
    id: 'waterville',
    name: 'Waterville Golf Links',
    shortName: 'Waterville',
    aliases: ['waterville gl'],
    location: 'Waterville, Ireland',
    architect: 'Eddie Hackett / Tom Fazio',
    logo: '🍀',
    logoUrl: '',
  },
  {
    id: 'tralee',
    name: 'Tralee Golf Club',
    shortName: 'Tralee',
    aliases: ['tralee gc'],
    location: 'Ardfert, Ireland',
    architect: 'Arnold Palmer',
    logo: '🌊',
    logoUrl: '',
  },
  {
    id: 'royal-dublin',
    name: 'Royal Dublin Golf Club',
    shortName: 'Royal Dublin',
    aliases: ['royal dublin gc'],
    location: 'Dublin, Ireland',
    architect: 'H.S. Colt',
    logo: '☘️',
    logoUrl: '',
  },
  {
    id: 'county-sligo',
    name: 'County Sligo Golf Club',
    shortName: 'Rosses Point',
    aliases: ['rosses point', 'county sligo gc'],
    location: 'Rosses Point, Ireland',
    architect: 'H.S. Colt',
    logo: '🌊',
    logoUrl: '',
  },
  {
    id: 'enniscrone',
    name: 'Enniscrone Golf Club',
    shortName: 'Enniscrone',
    aliases: ['enniscrone gc'],
    location: 'Enniscrone, Ireland',
    architect: 'Eddie Hackett',
    logo: '🍀',
    logoUrl: '',
  },
  {
    id: 'royal-portrush-valley',
    name: 'Royal Portrush Golf Club (Valley)',
    shortName: 'Portrush Valley',
    aliases: ['portrush valley', 'royal portrush valley'],
    location: 'Portrush, Northern Ireland',
    architect: 'Harry Colt',
    logo: '🏰',
    logoUrl: '',
  },

  // ── Additional Continental Europe ────────────────────────────────────────
  {
    id: 'falsterbo',
    name: 'Falsterbo Golfklubb',
    shortName: 'Falsterbo',
    aliases: ['falsterbo gk'],
    location: 'Falsterbo, Sweden',
    architect: 'Gunnar Bauer',
    logo: '🌬️',
    logoUrl: '',
  },
  {
    id: 'halmstad',
    name: 'Halmstad Golfklubb (North)',
    shortName: 'Halmstad',
    aliases: ['halmstad gk', 'halmstad north'],
    location: 'Halmstad, Sweden',
    architect: 'Rafael Sundblom / Frank Pennink',
    logo: '🌲',
    logoUrl: '',
  },
  {
    id: 'sotogrande',
    name: 'Real Club de Golf Sotogrande',
    shortName: 'Sotogrande',
    aliases: ['real club sotogrande', 'sotogrande gc'],
    location: 'Sotogrande, Spain',
    architect: 'Robert Trent Jones Sr.',
    logo: '🫒',
    logoUrl: '',
  },
  {
    id: 'la-reserva-sotogrande',
    name: 'La Reserva Club de Sotogrande',
    shortName: 'La Reserva',
    aliases: ['la reserva sotogrande', 'la reserva club'],
    location: 'Sotogrande, Spain',
    architect: 'Cabell Robinson',
    logo: '🫒',
    logoUrl: '',
  },
  {
    id: 'real-san-sebastian',
    name: 'Real Golf Club de San Sebastian',
    shortName: 'Real San Sebastian',
    aliases: ['real san sebastian', 'san sebastian gc'],
    location: 'Hondarribia, Spain',
    architect: 'Pierre Hirigoyen',
    logo: '🌊',
    logoUrl: '',
  },
  {
    id: 'le-touquet-la-mer',
    name: 'Le Touquet Golf Resort (La Mer)',
    shortName: 'Le Touquet La Mer',
    aliases: ['le touquet', 'le touquet la mer'],
    location: 'Le Touquet, France',
    architect: 'Harry Colt',
    logo: '🥖',
    logoUrl: '',
  },
  {
    id: 'domaine-de-belesbat',
    name: 'Golf de Belesbat',
    shortName: 'Belesbat',
    aliases: ['domaine de belesbat', 'golf de belesbat'],
    location: 'Courdimanche-sur-Essonne, France',
    architect: 'Patrice Lambert',
    logo: '🥖',
    logoUrl: '',
  },
  {
    id: 'fontainebleau',
    name: 'Golf de Fontainebleau',
    shortName: 'Fontainebleau',
    aliases: ['fontainebleau gc'],
    location: 'Fontainebleau, France',
    architect: 'Tom Simpson',
    logo: '🥖',
    logoUrl: '',
  },
  {
    id: 'club-zur-vahr',
    name: 'Club zur Vahr (Garlstedter Heide)',
    shortName: 'Club zur Vahr',
    aliases: ['garlstedt', 'club zur vahr'],
    location: 'Bremen, Germany',
    architect: 'Bernhard von Limburger',
    logo: '🌲',
    logoUrl: '',
  },
  {
    id: 'pevero',
    name: 'Pevero Golf Club',
    shortName: 'Pevero',
    aliases: ['pevero gc', 'costa smeralda'],
    location: 'Sardinia, Italy',
    architect: 'Robert Trent Jones Sr.',
    logo: '🌊',
    logoUrl: '',
  },

  // ── Additional Asia / Middle East ────────────────────────────────────────
  {
    id: 'hokkaido-classic',
    name: 'Hokkaido Classic Golf Club',
    shortName: 'Hokkaido Classic',
    aliases: ['hokkaido classic gc'],
    location: 'Hokkaido, Japan',
    architect: 'Jack Nicklaus',
    logo: '🌸',
    logoUrl: '',
  },
  {
    id: 'naruo',
    name: 'Naruo Golf Club',
    shortName: 'Naruo',
    aliases: ['naruo gc'],
    location: 'Hyogo, Japan',
    architect: 'H.C. Crane / Charles Alison',
    logo: '🌸',
    logoUrl: '',
  },
  {
    id: 'yas-links',
    name: 'Yas Links Abu Dhabi',
    shortName: 'Yas Links',
    aliases: ['yas links abu dhabi', 'yas island'],
    location: 'Abu Dhabi, United Arab Emirates',
    architect: 'Kyle Phillips',
    logo: '🐪',
    logoUrl: '',
  },
  {
    id: 'doha-golf-club',
    name: 'Doha Golf Club',
    shortName: 'Doha Golf Club',
    aliases: ['doha gc'],
    location: 'Doha, Qatar',
    architect: 'Peter Harradine',
    logo: '🐪',
    logoUrl: '',
  },
  {
    id: 'emirates-majlis',
    name: 'Emirates Golf Club (Majlis)',
    shortName: 'Emirates Majlis',
    aliases: ['emirates gc', 'majlis course', 'dubai desert classic'],
    location: 'Dubai, United Arab Emirates',
    architect: 'Karl Litten',
    logo: '🐪',
    logoUrl: '',
  },
  {
    id: 'mission-hills-shenzhen',
    name: 'Mission Hills (World Cup)',
    shortName: 'Mission Hills',
    aliases: ['mission hills shenzhen', 'mission hills china'],
    location: 'Shenzhen, China',
    architect: 'Jack Nicklaus',
    logo: '🐉',
    logoUrl: '',
  },

  // ── Additional Resorts (Caribbean / Mexico / Latin America) ──────────────
  {
    id: 'diamante-dunes',
    name: 'Diamante Cabo San Lucas (Dunes)',
    shortName: 'Diamante Dunes',
    aliases: ['diamante', 'diamante dunes', 'cabo dunes'],
    location: 'Cabo San Lucas, Mexico',
    architect: 'Davis Love III',
    logo: '🏖️',
    logoUrl: '',
  },
  {
    id: 'cabot-saint-lucia',
    name: 'Cabot Saint Lucia (Point Hardy)',
    shortName: 'Cabot Saint Lucia',
    aliases: ['cabot saint lucia', 'point hardy', 'cabot st lucia'],
    location: 'Cap Estate, Saint Lucia',
    architect: 'Bill Coore & Ben Crenshaw',
    logo: '🌴',
    logoUrl: '',
  },
  {
    id: 'casa-de-campo-teeth',
    name: 'Casa de Campo (Teeth of the Dog)',
    shortName: 'Teeth of the Dog',
    aliases: ['teeth of the dog', 'casa de campo'],
    location: 'La Romana, Dominican Republic',
    architect: 'Pete Dye',
    logo: '🦷',
    logoUrl: '',
  },
  {
    id: 'punta-espada',
    name: 'Punta Espada Golf Club',
    shortName: 'Punta Espada',
    aliases: ['punta espada gc', 'cap cana'],
    location: 'Cap Cana, Dominican Republic',
    architect: 'Jack Nicklaus',
    logo: '⚔️',
    logoUrl: '',
  },
  {
    id: 'country-club-bogota',
    name: 'Country Club de Bogota',
    shortName: 'CC de Bogota',
    aliases: ['country club bogota', 'cc de bogota'],
    location: 'Bogota, Colombia',
    architect: 'Robert Trent Jones Sr.',
    logo: '🌄',
    logoUrl: '',
  },

  // ── Additional Australia / New Zealand ───────────────────────────────────
  {
    id: 'royal-melbourne-east',
    name: 'Royal Melbourne Golf Club (East)',
    shortName: 'Royal Melbourne (East)',
    aliases: ['royal melbourne east', 'royal melbourne east course'],
    location: 'Black Rock, Australia',
    architect: 'Alex Russell',
    logo: '🦘',
    logoUrl: '',
  },
  {
    id: 'victoria-golf-club',
    name: 'Victoria Golf Club',
    shortName: 'Victoria',
    aliases: ['victoria gc melbourne'],
    location: 'Cheltenham, Australia',
    architect: 'William Meader / Alister MacKenzie',
    logo: '🦘',
    logoUrl: '',
  },
  {
    id: 'metropolitan-melbourne',
    name: 'Metropolitan Golf Club',
    shortName: 'Metropolitan',
    aliases: ['metropolitan gc'],
    location: 'South Oakleigh, Australia',
    architect: 'J.B. Mackenzie / Dick Wilson',
    logo: '🦘',
    logoUrl: '',
  },
  {
    id: 'ellerston',
    name: 'Ellerston Golf Course',
    shortName: 'Ellerston',
    aliases: ['ellerston gc'],
    location: 'Ellerston, Australia',
    architect: 'Greg Norman',
    logo: '🐎',
    logoUrl: '',
  },
  {
    id: 'te-arai-south',
    name: 'Te Arai Links (South)',
    shortName: 'Te Arai South',
    aliases: ['te arai south', 'te arai south course'],
    location: 'Te Arai, New Zealand',
    architect: 'Bill Coore & Ben Crenshaw',
    logo: '🌊',
    logoUrl: '',
  },
  {
    id: 'te-arai-north',
    name: 'Te Arai Links (North)',
    shortName: 'Te Arai North',
    aliases: ['te arai north', 'te arai north course'],
    location: 'Te Arai, New Zealand',
    architect: 'Tom Doak',
    logo: '🌊',
    logoUrl: '',
  },
  {
    id: 'paraparaumu-beach',
    name: 'Paraparaumu Beach Golf Club',
    shortName: 'Paraparaumu Beach',
    aliases: ['paraparaumu beach gc', 'parap'],
    location: 'Paraparaumu, New Zealand',
    architect: 'Alex Russell',
    logo: '🌊',
    logoUrl: '',
  },

  // ── Additional Canada ────────────────────────────────────────────────────
  {
    id: 'national-golf-club-canada',
    name: 'The National Golf Club of Canada',
    shortName: 'The National (Canada)',
    aliases: ['national golf club canada', 'national gc canada'],
    location: 'Woodbridge, Ontario, Canada',
    architect: 'Tom Fazio & George Fazio',
    logo: '🍁',
    logoUrl: '',
  },
  {
    id: 'highlands-links',
    name: 'Cape Breton Highlands Links',
    shortName: 'Highlands Links',
    aliases: ['cape breton highlands links', 'highlands links'],
    location: 'Ingonish Beach, Nova Scotia, Canada',
    architect: 'Stanley Thompson',
    logo: '🍁',
    logoUrl: '',
  },
  {
    id: 'jasper-park',
    name: 'Fairmont Jasper Park Lodge Golf Course',
    shortName: 'Jasper Park',
    aliases: ['jasper park lodge', 'jasper park golf'],
    location: 'Jasper, Alberta, Canada',
    architect: 'Stanley Thompson',
    logo: '🍁',
    logoUrl: '',
  },
  {
    id: 'banff-springs',
    name: 'Fairmont Banff Springs Golf Course',
    shortName: 'Banff Springs',
    aliases: ['banff springs', 'fairmont banff'],
    location: 'Banff, Alberta, Canada',
    architect: 'Stanley Thompson',
    logo: '🏔️',
    logoUrl: '',
  },
  {
    id: 'lido',
    name: 'The Lido',
    shortName: 'The Lido',
    aliases: ['lido', 'the lido', 'lido club'],
    location: 'Nekoosa, Wisconsin',
    architect: 'C.B. Macdonald (Tom Doak reconstruction)',
    logo: '🧜',
    logoUrl: '',
  },
  {
    id: 'old-barnwell',
    name: 'Old Barnwell',
    shortName: 'Old Barnwell',
    aliases: ['old barnwell', 'barnwell'],
    location: 'Aiken, South Carolina',
    architect: 'Brian Schneider & Blake Conant',
    logo: '🌲',
    logoUrl: '',
  },
  {
    id: 'mcarthur',
    name: 'McArthur Golf Club',
    shortName: 'McArthur',
    aliases: ['mcarthur', 'mcarthur golf'],
    location: 'Hobe Sound, Florida',
    architect: 'Tom Fazio & Nick Price',
    logo: '🥛',
    logoUrl: '',
  },
  {
    id: 'stanwich',
    name: 'The Stanwich Club',
    shortName: 'Stanwich',
    aliases: ['stanwich', 'the stanwich club'],
    location: 'Greenwich, Connecticut',
    architect: 'William Gordon & David Gordon',
    logo: '🧙',
    logoUrl: '',
  },
  {
    id: 'philadelphia-cricket',
    name: 'Philadelphia Cricket Club (Wissahickon)',
    shortName: 'Philadelphia Cricket',
    aliases: ['philadelphia cricket', 'pcc', 'wissahickon'],
    location: 'Flourtown, Pennsylvania',
    architect: 'A.W. Tillinghast',
    logo: '🏏',
    logoUrl: '',
  },
  {
    id: 'crooked-stick',
    name: 'Crooked Stick Golf Club',
    shortName: 'Crooked Stick',
    aliases: ['crooked stick'],
    location: 'Carmel, Indiana',
    architect: 'Pete Dye',
    logo: '🏌️',
    logoUrl: '',
  },
  {
    id: 'liberty-national',
    name: 'Liberty National Golf Club',
    shortName: 'Liberty National',
    aliases: ['liberty national', 'libnat'],
    location: 'Jersey City, New Jersey',
    architect: 'Tom Kite & Bob Cupp',
    logo: '🗽',
    logoUrl: '',
  },
  {
    id: 'yale',
    name: 'Yale Golf Course',
    shortName: 'Yale',
    aliases: ['yale', 'yale golf', 'yale university golf'],
    location: 'New Haven, Connecticut',
    architect: 'C.B. Macdonald & Seth Raynor',
    logo: '🎓',
    logoUrl: '',
  },

  // ── Additions: user-curated US courses with real logos ───────────────
  {
    id: 'bellerive',
    name: 'Bellerive Country Club',
    shortName: 'Bellerive',
    aliases: ['bellerive cc'],
    location: 'St. Louis, Missouri',
    architect: 'Robert Trent Jones Sr.',
    logo: '⛳',
    logoUrl: '',
  },
  {
    id: 'berkeley-hall',
    name: 'Berkeley Hall Club',
    shortName: 'Berkeley Hall',
    aliases: ['berkeley hall'],
    location: 'Bluffton, South Carolina',
    architect: 'Tom Fazio',
    logo: '⛳',
    logoUrl: '',
  },
  {
    id: 'black-sheep',
    name: 'Black Sheep Golf Club',
    shortName: 'Black Sheep',
    aliases: ['black sheep gc'],
    location: 'Sugar Grove, Illinois',
    architect: 'Hurdzan & Fry',
    logo: '🐑',
    logoUrl: '',
  },
  {
    id: 'boston-golf-club',
    name: 'Boston Golf Club',
    shortName: 'Boston',
    aliases: ['boston gc'],
    location: 'Hingham, Massachusetts',
    architect: 'Gil Hanse',
    logo: '⛳',
    logoUrl: '',
  },
  {
    id: 'broomsedge',
    name: 'Broomsedge',
    shortName: 'Broomsedge',
    aliases: ['broomsedge gc'],
    location: 'Aiken, South Carolina',
    architect: 'King-Collins',
    logo: '⛳',
    logoUrl: '',
  },
  {
    id: 'burning-tree',
    name: 'Burning Tree Club',
    shortName: 'Burning Tree',
    aliases: ['burning tree'],
    location: 'Bethesda, Maryland',
    architect: 'Alister MacKenzie & Devereux Emmet',
    logo: '🔥',
    logoUrl: '',
  },
  {
    id: 'calusa-pines',
    name: 'Calusa Pines Golf Club',
    shortName: 'Calusa Pines',
    aliases: ['calusa'],
    location: 'Naples, Florida',
    architect: 'Hurdzan & Fry',
    logo: '🌲',
    logoUrl: '',
  },
  {
    id: 'dooks',
    name: 'Dooks Golf Club',
    shortName: 'Dooks',
    aliases: ['dooks gc'],
    location: 'Glenbeigh, County Kerry, Ireland',
    architect: 'Eddie Hackett',
    logo: '🍀',
    logoUrl: '',
  },
  {
    id: 'essex-county',
    name: 'Essex County Country Club',
    shortName: 'Essex County',
    aliases: ['essex'],
    location: 'West Orange, New Jersey',
    architect: 'Donald Ross',
    logo: '⛳',
    logoUrl: '',
  },
  {
    id: 'flossmoor',
    name: 'Flossmoor Country Club',
    shortName: 'Flossmoor Country Club',
    aliases: ['flossmoor', 'flossmoor cc'],
    location: 'Flossmoor, Illinois',
    architect: 'Herbert Tweedie',
    logo: '⛳',
    logoUrl: '',
  },
  {
    id: 'gamble-sands',
    name: 'Gamble Sands',
    shortName: 'Gamble Sands',
    aliases: ['gamble'],
    location: 'Brewster, Washington',
    architect: 'David McLay Kidd',
    logo: '🌾',
    logoUrl: '',
  },
  {
    id: 'interlachen',
    name: 'Interlachen Country Club',
    shortName: 'Interlachen',
    aliases: ['interlachen cc'],
    location: 'Edina, Minnesota',
    architect: 'Donald Ross',
    logo: '⛳',
    logoUrl: '',
  },
  {
    id: 'kittansett',
    name: 'The Kittansett Club',
    shortName: 'Kittansett',
    aliases: ['kittansett club'],
    location: 'Marion, Massachusetts',
    architect: 'Frederick Hood',
    logo: '⚓',
    logoUrl: '',
  },
  {
    id: 'lost-dunes',
    name: 'Lost Dunes Golf Club',
    shortName: 'Lost Dunes',
    aliases: ['lost dunes gc'],
    location: 'Bridgman, Michigan',
    architect: 'Tom Doak',
    logo: '🏖️',
    logoUrl: '',
  },
  {
    id: 'myopia-hunt',
    name: 'Myopia Hunt Club',
    shortName: 'Myopia Hunt',
    aliases: ['myopia', 'myopia hunt', 'myopia hunt club', 'myopia club'],
    location: 'South Hamilton, Massachusetts',
    architect: 'Herbert Leeds',
    logo: '🦊',
    logoUrl: '',
  },
  {
    id: 'naples-national',
    name: 'Naples National Golf Club',
    shortName: 'Naples National',
    aliases: ['naples national gc'],
    location: 'Naples, Florida',
    architect: 'Tom Fazio',
    logo: '🌴',
    logoUrl: '',
  },
  {
    id: 'old-elm',
    name: 'Old Elm Club',
    shortName: 'Old Elm',
    aliases: ['old elm gc'],
    location: 'Highland Park, Illinois',
    architect: 'Harry S. Colt & Donald Ross',
    logo: '🌳',
    logoUrl: '',
  },
  {
    id: 'pacific-dunes',
    name: 'Pacific Dunes',
    shortName: 'Pacific Dunes',
    aliases: ['bandon pacific dunes'],
    location: 'Bandon, Oregon',
    architect: 'Tom Doak',
    logo: '🌊',
    logoUrl: '',
  },
  {
    id: 'piping-rock',
    name: 'Piping Rock Club',
    shortName: 'Piping Rock',
    aliases: ['piping rock'],
    location: 'Locust Valley, New York',
    architect: 'C.B. Macdonald',
    logo: '🪈',
    logoUrl: '',
  },
  {
    id: 'rich-harvest-farms',
    name: 'Rich Harvest Farms',
    shortName: 'Rich Harvest',
    aliases: ['rich harvest'],
    location: 'Sugar Grove, Illinois',
    architect: 'Jerry Rich',
    logo: '🌾',
    logoUrl: '',
  },
  {
    id: 'sage-valley',
    name: 'Sage Valley Golf Club',
    shortName: 'Sage Valley',
    aliases: ['sage', 'sage valley', 'sage valley club'],
    location: 'Graniteville, South Carolina',
    architect: 'Tom Fazio',
    logo: '🌿',
    logoUrl: '',
  },
  {
    id: 'scioto',
    name: 'Scioto Country Club',
    shortName: 'Scioto',
    aliases: ['scioto cc'],
    location: 'Columbus, Ohio',
    architect: 'Donald Ross',
    logo: '⛳',
    logoUrl: '',
  },
  {
    id: 'secession',
    name: 'Secession Golf Club',
    shortName: 'Secession',
    aliases: ['secession gc'],
    location: 'Beaufort, South Carolina',
    architect: 'Bruce Devlin & P.B. Dye',
    logo: '⛳',
    logoUrl: '',
  },
  {
    id: 'shoreacres',
    name: 'Shoreacres',
    shortName: 'Shoreacres',
    aliases: ['shore acres'],
    location: 'Lake Bluff, Illinois',
    architect: 'Seth Raynor',
    logo: '🌊',
    logoUrl: '',
  },
  {
    id: 'skene-valley',
    name: 'Skene Valley Country Club',
    shortName: 'Skene Valley',
    aliases: ['skene', 'skene valley cc'],
    location: 'Whitehall, New York',
    architect: 'William Mitchell',
    logo: '🦶',
    logoUrl: '',
  },
  {
    id: 'st-louis-cc',
    name: 'St. Louis Country Club',
    shortName: 'St. Louis CC',
    aliases: ['st louis country club', 'saint louis cc'],
    location: 'Ladue, Missouri',
    architect: 'C.B. Macdonald & Seth Raynor',
    logo: '⛳',
    logoUrl: '',
  },
  {
    id: 'stonewall-orchard',
    name: 'Stonewall Orchard Golf Club',
    shortName: 'Stonewall Orchard',
    aliases: ['stonewall'],
    location: 'Grayslake, Illinois',
    architect: 'Arthur Hills',
    logo: '🍎',
    logoUrl: '',
  },
  {
    id: 'alotian',
    name: 'The Alotian Club',
    shortName: 'Alotian',
    aliases: ['the alotian club'],
    location: 'Roland, Arkansas',
    architect: 'Tom Fazio',
    logo: '⛳',
    logoUrl: '',
  },
  {
    id: 'the-country-club',
    name: 'The Country Club',
    shortName: 'Brookline',
    aliases: ['country club brookline', 'tcc', 'the country club at brookline'],
    location: 'Brookline, Massachusetts',
    architect: 'William Campbell & Willie Park Jr.',
    logo: '⛳',
    logoUrl: '',
  },
  {
    id: 'dunes-club',
    name: 'The Dunes Club',
    shortName: 'Dunes Club (NJ)',
    aliases: ['the dunes club michigan'],
    location: 'New Buffalo, Michigan',
    architect: 'Dick Nugent',
    logo: '🏖️',
    logoUrl: '',
  },
  {
    id: 'the-hay',
    name: 'The Hay',
    shortName: 'The Hay',
    aliases: ['hay short course', 'pebble beach hay'],
    location: 'Pebble Beach, California',
    architect: 'Tiger Woods (TGR Design)',
    logo: '🌾',
    logoUrl: '',
  },
  {
    id: 'loxahatchee',
    name: 'The Loxahatchee Club',
    shortName: 'Loxahatchee',
    aliases: ['loxahatchee club'],
    location: 'Jupiter, Florida',
    architect: 'Jack Nicklaus',
    logo: '🌴',
    logoUrl: '',
  },
  {
    id: 'tree-farm',
    name: 'The Tree Farm',
    shortName: 'Tree Farm',
    aliases: ['the tree farm'],
    location: 'Aiken, South Carolina',
    architect: 'Tom Doak & Brian Schneider',
    logo: '🌲',
    logoUrl: '',
  },
  {
    id: 'vaquero',
    name: 'Vaquero Club',
    shortName: 'Vaquero',
    aliases: ['vaquero golf club'],
    location: 'Westlake, Texas',
    architect: 'Tom Fazio',
    logo: '🤠',
    logoUrl: '',
  },
];

// Helper used by the runtime when rendering a tile. Returns either the
// configured logoUrl, or the conventional asset path; the caller falls back
// to the emoji if the <img> 404s.
export function courseLogoUrl(course) {
  if (!course) return '';
  if (course.logoUrl) return course.logoUrl;
  return `/assets/logos/${course.id}.png`;
}
